-- data source (as of 2020-10-26):
-- 1. https://en.wikipedia.org/wiki/List_of_districts_of_Thailand
-- 2. https://en.wikipedia.org/wiki/List_of_districts_of_Bangkok

drop table if exists amphur;

CREATE TABLE amphur (
    province_th varchar(50),
    province_en varchar(50),
    region varchar(50),
    amphur_th varchar(50),
    amphur_en varchar(50)
);


INSERT INTO amphur VALUES ('กระบี่', 'Krabi', 'South', 'เกาะลันตา', 'Ko Lanta');
INSERT INTO amphur VALUES ('กระบี่', 'Krabi', 'South', 'เขาพนม', 'Khao Phanom');
INSERT INTO amphur VALUES ('กระบี่', 'Krabi', 'South', 'คลองท่อม', 'Khlong Thom');
INSERT INTO amphur VALUES ('กระบี่', 'Krabi', 'South', 'ปลายพระยา', 'Plai Phraya');
INSERT INTO amphur VALUES ('กระบี่', 'Krabi', 'South', 'เมืองกระบี่', 'Mueang Krabi');
INSERT INTO amphur VALUES ('กระบี่', 'Krabi', 'South', 'ลำทับ', 'Lam Thap');
INSERT INTO amphur VALUES ('กระบี่', 'Krabi', 'South', 'เหนือคลอง', 'Nuea Khlong');
INSERT INTO amphur VALUES ('กระบี่', 'Krabi', 'South', 'อ่าวลึก', 'Ao Luek');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'คลองเตย', 'Khlong Toei');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'คลองสาน', 'Khlong San');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'คลองสามวา', 'Khlong Sam Wa');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'คันนายาว', 'Khan Na Yao');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'จตุจักร', 'Chatuchak');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'จอมทอง', 'Chom Thong');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ดอนเมือง', 'Don Mueang');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ดินแดง', 'Din Daeng');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ดุสิต', 'Dusit');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ตลิ่งชัน', 'Taling Chan');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ทวีวัฒนา', 'Thawi Watthana');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ทุ่งครุ', 'Thung Khru');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ธนบุรี', 'Thon Buri');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางกอกน้อย', 'Bangkok Noi');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางกอกใหญ่', 'Bangkok Yai');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางกะปิ', 'Bang Kapi');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางขุนเทียน', 'Bang Khun Thian');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางเขน', 'Bang Khen');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางคอแหลม', 'Bang Kho Laem');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางแค', 'Bang Khae');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางซื่อ', 'Bang Sue');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางนา', 'Bang Na');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางบอน', 'Bang Bon');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางพลัด', 'Bang Phlat');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บางรัก', 'Bang Rak');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'บึงกุ่ม', 'Bueng Kum');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ปทุมวัน', 'Pathum Wan');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ประเวศ', 'Prawet');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ป้อมปราบศัตรูพ่าย', 'Pom Prap Sattru Phai');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'พญาไท', 'Phaya Thai');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'พระโขนง', 'Phra Khanong');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'พระนคร', 'Phra Nakhon');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ภาษีเจริญ', 'Phasi Charoen');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'มีนบุรี', 'Min Buri');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ยานนาวา', 'Yan Nawa');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ราชเทวี', 'Ratchathewi');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ราษฏร์บูรณะ', 'Rat Burana');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ลาดกระบัง', 'Lat Krabang');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ลาดพร้าว', 'Lat Phrao');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'วังทองหลาง', 'Wang Thonglang');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'วัฒนา', 'Watthana');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'สวนหลวง', 'Suan Luang');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'สะพานสูง', 'Saphan Sung');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'สัมพันธวงศ์', 'Samphanthawong');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'สาทร', 'Sathon');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'สายไหม', 'Sai Mai');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'หนองแขม', 'Nong Khaem');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'หนองจอก', 'Nong Chok');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'หลักสี่', 'Lak Si');
INSERT INTO amphur VALUES ('กรุงเทพมหานคร', 'Bangkok', 'Centre', 'ห้วยขวาง', 'Huai Khwang');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'ด่านมะขามเตี้ย', 'Dan Makham Tia');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'ทองผาภูมิ', 'Thong Pha Phum');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'ท่าม่วง', 'Tha Muang');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'ท่ามะกา', 'Tha Maka');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'ไทรโยค', 'Sai Yok');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'บ่อพลอย', 'Bo Phloi');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'พนมทวน', 'Phanom Thuan');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'เมืองกาญจนบุรี', 'Mueang Kanchanaburi');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'เลาขวัญ', 'Lao Khwan');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'ศรีสวัสดิ์', 'Si Sawat');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'สังขละบุรี', 'Sangkhla Buri');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'หนองปรือ', 'Nong Prue');
INSERT INTO amphur VALUES ('กาญจนบุรี', 'Kanchanaburi', 'West', 'ห้วยกระเจา', 'Huai Krachao');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'กมลาไสย', 'Kamalasai');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'กุฉินารายณ์', 'Kuchinarai');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'เขาวง', 'Khao Wong');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'คำม่วง', 'Kham Muang');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'ฆ้องชัย', 'Khong Chai');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'ดอนจาน', 'Don Chan');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'ท่าคันโท', 'Tha Khantho');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'นาคู', 'Na Khu');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'นามน', 'Na Mon');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'เมืองกาฬสินธุ์', 'Mueang Kalasin');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'ยางตลาด', 'Yang Talat');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'ร่องคำ', 'Rong Kham');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'สมเด็จ', 'Somdet');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'สหัสขันธ์', 'Sahatsakhan');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'สามชัย', 'Sam Chai');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'หนองกุงศรี', 'Nong Kung Si');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'ห้วยผึ้ง', 'Huai Phueng');
INSERT INTO amphur VALUES ('กาฬสินธุ์', 'Kalasin', 'North-East', 'ห้วยเม็ก', 'Huai Mek');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'โกสัมพีนคร', 'Kosamphi Nakhon');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'ขาณุวรลักษบุรี', 'Khanu Woralaksaburi');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'คลองขลุง', 'Khlong Khlung');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'คลองลาน', 'Khlong Lan');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'ทรายทองวัฒนา', 'Sai Thong Watthana');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'ไทรงาม', 'Sai Ngam');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'บึงสามัคคี', 'Bueng Samakkhi');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'ปางศิลาทอง', 'Pang Sila Thong');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'พรานกระต่าย', 'Phran Kratai');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'เมืองกำแพงเพชร', 'Mueang Kamphaeng Phet');
INSERT INTO amphur VALUES ('กำแพงเพชร', 'Kamphaeng Phet', 'Centre', 'ลานกระบือ', 'Lan Krabue');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'กระนวน', 'Kranuan');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'เขาสวนกวาง', 'Khao Suan Kwang');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'โคกโพธิ์ไชย', 'Khok Pho Chai');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'ชนบท', 'Chonnabot');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'ชุมแพ', 'Chum Phae');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'ซำสูง', 'Sam Sung');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'น้ำพอง', 'Nam Phong');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'โนนศิลา', 'Non Sila');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'บ้านไผ่', 'Ban Phai');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'บ้านฝาง', 'Ban Fang');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'บ้านแฮด', 'Ban Haet');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'เปือยน้อย', 'Pueai Noi');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'พระยืน', 'Phra Yuen');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'พล', 'Phon');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'ภูผาม่าน', 'Phu Pha Man');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'ภูเวียง', 'Phu Wiang');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'มัญจาคีรี', 'Mancha Khiri');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'เมืองขอนแก่น', 'Mueang Khon Kaen');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'เวียงเก่า', 'Wiang Kao');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'แวงน้อย', 'Waeng Noi');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'แวงใหญ่', 'Waeng Yai');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'สีชมพู', 'Si Chomphu');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'หนองนาคำ', 'Nong Na Kham');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'หนองเรือ', 'Nong Ruea');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'หนองสองห้อง', 'Nong Song Hong');
INSERT INTO amphur VALUES ('ขอนแก่น', 'Khon Kaen', 'North-East', 'อุบลรัตน์', 'Ubolratana');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'แก่งหางแมว', 'Kaeng Hang Maeo');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'ขลุง', 'Khlung');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'เขาคิชฌกูฏ', 'Khao Khitchakut');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'ท่าใหม่', 'Tha Mai');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'นายายอาม', 'Na Yai Am');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'โป่งน้ำร้อน', 'Pong Nam Ron');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'มะขาม', 'Makham');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'เมืองจันทบุรี', 'Mueang Chanthaburi');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'สอยดาว', 'Soi Dao');
INSERT INTO amphur VALUES ('จันทบุรี', 'Chanthaburi', 'East', 'แหลมสิงห์', 'Laem Sing');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'คลองเขื่อน', 'Khlong Khuean');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'ท่าตะเกียบ', 'Tha Takiap');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'บางคล้า', 'Bang Khla');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'บางน้ำเปรี้ยว', 'Bang Nam Priao');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'บางปะกง', 'Bang Pakong');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'บ้านโพธิ์', 'Ban Pho');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'แปลงยาว', 'Plaeng Yao');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'พนมสารคาม', 'Phanom Sarakham');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'เมืองฉะเชิงเทรา', 'Mueang Chachoengsao');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'ราชสาส์น', 'Ratchasan');
INSERT INTO amphur VALUES ('ฉะเชิงเทรา', 'Chachoengsao', 'East', 'สนามชัยเขต', 'Sanam Chai Khet');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'เกาะจันทร์', 'Ko Chan');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'เกาะสีชัง', 'Ko Sichang');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'บ่อทอง', 'Bo Thong');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'บางละมุง', 'Bang Lamung');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'บ้านบึง', 'Ban Bueng');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'พนัสนิคม', 'Phanat Nikhom');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'พานทอง', 'Phan Thong');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'เมืองชลบุรี', 'Mueang Chonburi');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'ศรีราชา', 'Si Racha');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'สัตหีบ', 'Sattahip');
INSERT INTO amphur VALUES ('ชลบุรี', 'Chonburi', 'East', 'หนองใหญ่', 'Nong Yai');
INSERT INTO amphur VALUES ('ชัยนาท', 'Chainat', 'Centre', 'เนินขาม', 'Noen Kham');
INSERT INTO amphur VALUES ('ชัยนาท', 'Chainat', 'Centre', 'มโนรมย์', 'Manorom');
INSERT INTO amphur VALUES ('ชัยนาท', 'Chainat', 'Centre', 'เมืองชัยนาท', 'Mueang Chainat');
INSERT INTO amphur VALUES ('ชัยนาท', 'Chainat', 'Centre', 'วัดสิงห์', 'Wat Sing');
INSERT INTO amphur VALUES ('ชัยนาท', 'Chainat', 'Centre', 'สรรคบุรี', 'Sankhaburi');
INSERT INTO amphur VALUES ('ชัยนาท', 'Chainat', 'Centre', 'สรรพยา', 'Sapphaya');
INSERT INTO amphur VALUES ('ชัยนาท', 'Chainat', 'Centre', 'หนองมะโมง', 'Nong Mamong');
INSERT INTO amphur VALUES ('ชัยนาท', 'Chainat', 'Centre', 'หันคา', 'Hankha');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'เกษตรสมบูรณ์', 'Kaset Sombun');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'แก้งคร้อ', 'Kaeng Khro');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'คอนสวรรค์', 'Khon Sawan');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'คอนสาร', 'Khon San');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'จัตุรัส', 'Chatturat');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'ซับใหญ่', 'Sap Yai');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'เทพสถิต', 'Thep Sathit');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'เนินสง่า', 'Noen Sa-nga');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'บ้านเขว้า', 'Ban Khwao');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'บ้านแท่น', 'Ban Thaen');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'บำเหน็จณรงค์', 'Bamnet Narong');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'ภักดีชุมพล', 'Phakdi Chumphon');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'ภูเขียว', 'Phu Khiao');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'เมืองชัยภูมิ', 'Mueang Chaiyaphum');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'หนองบัวแดง', 'Nong Bua Daeng');
INSERT INTO amphur VALUES ('ชัยภูมิ', 'Chaiyaphum', 'North-East', 'หนองบัวระเหว', 'Nong Bua Rawe');
INSERT INTO amphur VALUES ('ชุมพร', 'Chumphon', 'South', 'ท่าแซะ', 'Tha Sae');
INSERT INTO amphur VALUES ('ชุมพร', 'Chumphon', 'South', 'ทุ่งตะโก', 'Thung Tako');
INSERT INTO amphur VALUES ('ชุมพร', 'Chumphon', 'South', 'ปะทิว', 'Pathio');
INSERT INTO amphur VALUES ('ชุมพร', 'Chumphon', 'South', 'พะโต๊ะ', 'Phato');
INSERT INTO amphur VALUES ('ชุมพร', 'Chumphon', 'South', 'เมืองชุมพร', 'Mueang Chumphon');
INSERT INTO amphur VALUES ('ชุมพร', 'Chumphon', 'South', 'ละแม', 'Lamae');
INSERT INTO amphur VALUES ('ชุมพร', 'Chumphon', 'South', 'สวี', 'Sawi');
INSERT INTO amphur VALUES ('ชุมพร', 'Chumphon', 'South', 'หลังสวน', 'Lang Suan');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'ขุนตาล', 'Khun Tan');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'เชียงของ', 'Chiang Khong');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'เชียงแสน', 'Chiang Saen');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'ดอยหลวง', 'Doi Luang');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'เทิง', 'Thoeng');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'ป่าแดด', 'Pa Daet');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'พญาเม็งราย', 'Phaya Mengrai');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'พาน', 'Phan');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'เมืองเชียงราย', 'Mueang Chiang Rai');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'แม่จัน', 'Mae Chan');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'แม่ฟ้าหลวง', 'Mae Fa Luang');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'แม่ลาว', 'Mae Lao');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'แม่สรวย', 'Mae Suai');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'แม่สาย', 'Mae Sai');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'เวียงแก่น', 'Wiang Kaen');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'เวียงชัย', 'Wiang Chai');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'เวียงเชียงรุ้ง', 'Wiang Chiang Rung');
INSERT INTO amphur VALUES ('เชียงราย', 'Chiang Rai', 'North', 'เวียงป่าเป้า', 'Wiang Pa Pao');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'กัลยาณิวัฒนา', 'Galyani Vadhana');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'จอมทอง', 'Chom Thong');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'เชียงดาว', 'Chiang Dao');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'ไชยปราการ', 'Chai Prakan');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'ดอยเต่า', 'Doi Tao');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'ดอยสะเก็ด', 'Doi Saket');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'ดอยหล่อ', 'Doi Lo');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'ฝาง', 'Fang');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'พร้าว', 'Phrao');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'เมืองเชียงใหม่', 'Mueang Chiang Mai');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'แม่แจ่ม', 'Mae Chaem');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'แม่แตง', 'Mae Taeng');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'แม่ริม', 'Mae Rim');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'แม่วาง', 'Mae Wang');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'แม่ออน', 'Mae On');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'แม่อาย', 'Mae Ai');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'เวียงแหง', 'Wiang Haeng');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'สะเมิง', 'Samoeng');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'สันกำแพง', 'San Kamphaeng');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'สันทราย', 'San Sai');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'สันป่าตอง', 'San Pa Tong');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'สารภี', 'Saraphi');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'หางดง', 'Hang Dong');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'อมก๋อย', 'Omkoi');
INSERT INTO amphur VALUES ('เชียงใหม่', 'Chiang Mai', 'North', 'ฮอด', 'Hot');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'กันตัง', 'Kantang');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'นาโยง', 'Na Yong');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'ปะเหลียน', 'Palian');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'เมืองตรัง', 'Mueang Trang');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'ย่านตาขาว', 'Yan Ta Khao');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'รัษฎา', 'Ratsada');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'วังวิเศษ', 'Wang Wiset');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'สิเกา', 'Sikao');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'ห้วยยอด', 'Huai Yot');
INSERT INTO amphur VALUES ('ตรัง', 'Trang', 'South', 'หาดสำราญ', 'Hat Samran');
INSERT INTO amphur VALUES ('ตราด', 'Trat', 'East', 'เกาะกูด', 'Ko Kut');
INSERT INTO amphur VALUES ('ตราด', 'Trat', 'East', 'เกาะช้าง', 'Ko Chang');
INSERT INTO amphur VALUES ('ตราด', 'Trat', 'East', 'เขาสมิง', 'Khao Saming');
INSERT INTO amphur VALUES ('ตราด', 'Trat', 'East', 'คลองใหญ่', 'Khlong Yai');
INSERT INTO amphur VALUES ('ตราด', 'Trat', 'East', 'บ่อไร่', 'Bo Rai');
INSERT INTO amphur VALUES ('ตราด', 'Trat', 'East', 'เมืองตราด', 'Mueang Trat');
INSERT INTO amphur VALUES ('ตราด', 'Trat', 'East', 'แหลมงอบ', 'Laem Ngop');
INSERT INTO amphur VALUES ('ตาก', 'Tak', 'West', 'ท่าสองยาง', 'Tha Song Yang');
INSERT INTO amphur VALUES ('ตาก', 'Tak', 'West', 'บ้านตาก', 'Ban Tak');
INSERT INTO amphur VALUES ('ตาก', 'Tak', 'West', 'พบพระ', 'Phop Phra');
INSERT INTO amphur VALUES ('ตาก', 'Tak', 'West', 'เมืองตาก', 'Mueang Tak');
INSERT INTO amphur VALUES ('ตาก', 'Tak', 'West', 'แม่ระมาด', 'Mae Ramat');
INSERT INTO amphur VALUES ('ตาก', 'Tak', 'West', 'แม่สอด', 'Mae Sot');
INSERT INTO amphur VALUES ('ตาก', 'Tak', 'West', 'วังเจ้า', 'Wang Chao');
INSERT INTO amphur VALUES ('ตาก', 'Tak', 'West', 'สามเงา', 'Sam Ngao');
INSERT INTO amphur VALUES ('ตาก', 'Tak', 'West', 'อุ้มผาง', 'Umphang');
INSERT INTO amphur VALUES ('นครนายก', 'Nakhon Nayok', 'Centre', 'บ้านนา', 'Ban Na');
INSERT INTO amphur VALUES ('นครนายก', 'Nakhon Nayok', 'Centre', 'ปากพลี', 'Pak Phli');
INSERT INTO amphur VALUES ('นครนายก', 'Nakhon Nayok', 'Centre', 'เมืองนครนายก', 'Mueang Nakhon Nayok');
INSERT INTO amphur VALUES ('นครนายก', 'Nakhon Nayok', 'Centre', 'องครักษ์', 'Ongkharak');
INSERT INTO amphur VALUES ('นครปฐม', 'Nakhon Pathom', 'Centre', 'กำแพงแสน', 'Kamphaeng Saen');
INSERT INTO amphur VALUES ('นครปฐม', 'Nakhon Pathom', 'Centre', 'ดอนตูม', 'Don Tum');
INSERT INTO amphur VALUES ('นครปฐม', 'Nakhon Pathom', 'Centre', 'นครชัยศรี', 'Nakhon Chai Si');
INSERT INTO amphur VALUES ('นครปฐม', 'Nakhon Pathom', 'Centre', 'บางเลน', 'Bang Len');
INSERT INTO amphur VALUES ('นครปฐม', 'Nakhon Pathom', 'Centre', 'พุทธมณฑล', 'Phutthamonthon');
INSERT INTO amphur VALUES ('นครปฐม', 'Nakhon Pathom', 'Centre', 'เมืองนครปฐม', 'Mueang Nakhon Pathom');
INSERT INTO amphur VALUES ('นครปฐม', 'Nakhon Pathom', 'Centre', 'สามพราน', 'Sam Phran');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'ท่าอุเทน', 'Tha Uthen');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'ธาตุพนม', 'That Phanom');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'นาแก', 'Na Kae');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'นาทม', 'Na Thom');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'นาหว้า', 'Na Wa');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'บ้านแพง', 'Ban Phaeng');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'ปลาปาก', 'Pla Pak');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'โพนสวรรค์', 'Phon Sawan');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'เมืองนครพนม', 'Mueang Nakhon Phanom');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'เรณูนคร', 'Renu Nakhon');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'วังยาง', 'Wang Yang');
INSERT INTO amphur VALUES ('นครพนม', 'Nakhon Phanom', 'North-East', 'ศรีสงคราม', 'Si Songkhram');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'แก้งสนามนาง', 'Kaeng Sanam Nang');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ขามทะเลสอ', 'Kham Thale So');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ขามสะแกแสง', 'Kham Sakaesaeng');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'คง', 'Khong');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ครบุรี', 'Khon Buri');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'จักราช', 'Chakkarat');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ชุมพวง', 'Chum Phuang');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'โชคชัย', 'Chok Chai');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ด่านขุนทด', 'Dan Khun Thot');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'เทพารักษ์', 'Thepharak');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'โนนแดง', 'Non Daeng');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'โนนไทย', 'Non Thai');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'โนนสูง', 'Non Sung');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'บัวลาย', 'Bua Lai');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'บัวใหญ่', 'Bua Yai');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'บ้านเหลื่อม', 'Ban Lueam');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ประทาย', 'Prathai');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ปักธงชัย', 'Pak Thong Chai');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ปากช่อง', 'Pak Chong');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'พระทองคำ', 'Phra Thong Kham');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'พิมาย', 'Phimai');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'เมืองนครราชสีมา', 'Mueang Nakhon Ratchasima');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'เมืองยาง', 'Mueang Yang');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ลำทะเมนชัย', 'Lam Thamenchai');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'วังน้ำเขียว', 'Wang Nam Khiao');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'สีคิ้ว', 'Sikhio');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'สีดา', 'Sida');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'สูงเนิน', 'Sung Noen');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'เสิงสาง', 'Soeng Sang');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'หนองบุญมาก', 'Nong Bun Mak');
INSERT INTO amphur VALUES ('นครราชสีมา', 'Nakhon Ratchasima', 'North-East', 'ห้วยแถลง', 'Huai Thalaeng');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ขนอม', 'Khanom');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'จุฬาภรณ์', 'Chulabhorn');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ฉวาง', 'Chawang');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ชะอวด', 'Cha-uat');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ช้างกลาง', 'Chang Klang');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'เชียรใหญ่', 'Chian Yai');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ถ้ำพรรณรา', 'Tham Phannara');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ท่าศาลา', 'Tha Sala');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ทุ่งสง', 'Thung Song');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ทุ่งใหญ่', 'Thung Yai');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'นบพิตำ', 'Nopphitam');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'นาบอน', 'Na Bon');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'บางขัน', 'Bang Khan');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ปากพนัง', 'Pak Phanang');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'พรหมคีรี', 'Phrom Khiri');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'พระพรหม', 'Phra Phrom');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'พิปูน', 'Phipun');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'เมืองนครศรีธรรมราช', 'Mueang Nakhon Si Thammarat');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ร่อนพิบูลย์', 'Ron Phibun');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'ลานสกา', 'Lan Saka');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'สิชล', 'Sichon');
INSERT INTO amphur VALUES ('นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South', 'หัวไทร', 'Hua Sai');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'เก้าเลี้ยว', 'Kao Liao');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'โกรกพระ', 'Krok Phra');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'ชุมตาบง', 'Chum Ta Bong');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'ชุมแสง', 'Chum Saeng');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'ตากฟ้า', 'Tak Fa');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'ตาคลี', 'Takhli');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'ท่าตะโก', 'Tha Tako');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'บรรพตพิสัย', 'Banphot Phisai');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'พยุหะคีรี', 'Phayuha Khiri');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'ไพศาลี', 'Phaisali');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'เมืองนครสวรรค์', 'Mueang Nakhon Sawan');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'แม่เปิน', 'Mae Poen');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'แม่วงก์', 'Mae Wong');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'ลาดยาว', 'Lat Yao');
INSERT INTO amphur VALUES ('นครสวรรค์', 'Nakhon Sawan', 'Centre', 'หนองบัว', 'Nong Bua');
INSERT INTO amphur VALUES ('นนทบุรี', 'Nonthaburi', 'Centre', 'ไทรน้อย', 'Sai Noi');
INSERT INTO amphur VALUES ('นนทบุรี', 'Nonthaburi', 'Centre', 'บางกรวย', 'Bang Kruai');
INSERT INTO amphur VALUES ('นนทบุรี', 'Nonthaburi', 'Centre', 'บางบัวทอง', 'Bang Bua Thong');
INSERT INTO amphur VALUES ('นนทบุรี', 'Nonthaburi', 'Centre', 'บางใหญ่', 'Bang Yai');
INSERT INTO amphur VALUES ('นนทบุรี', 'Nonthaburi', 'Centre', 'ปากเกร็ด', 'Pak Kret');
INSERT INTO amphur VALUES ('นนทบุรี', 'Nonthaburi', 'Centre', 'เมืองนนทบุรี', 'Mueang Nonthaburi');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'จะแนะ', 'Chanae');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'เจาะไอร้อง', 'Cho-airong');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'ตากใบ', 'Tak Bai');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'บาเจาะ', 'Bacho');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'เมืองนราธิวาส', 'Mueang Narathiwat');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'ยี่งอ', 'Yi-ngo');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'ระแงะ', 'Ra-ngae');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'รือเสาะ', 'Rueso');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'แว้ง', 'Waeng');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'ศรีสาคร', 'Si Sakhon');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'สุคิริน', 'Sukhirin');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'สุไหงโก-ลก', 'Su-ngai Kolok');
INSERT INTO amphur VALUES ('นราธิวาส', 'Narathiwat', 'South', 'สุไหงปาดี', 'Su-ngai Padi');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'เชียงกลาง', 'Chiang Klang');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'ท่าวังผา', 'Tha Wang Pha');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'ทุ่งช้าง', 'Thung Chang');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'นาน้อย', 'Na Noi');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'นาหมื่น', 'Na Muen');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'บ่อเกลือ', 'Bo Kluea');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'บ้านหลวง', 'Ban Luang');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'ปัว', 'Pua');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'ภูเพียง', 'Phu Phiang');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'เมืองน่าน', 'Mueang Nan');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'แม่จริม', 'Mae Charim');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'เวียงสา', 'Wiang Sa');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'สองแคว', 'Song Khwae');
INSERT INTO amphur VALUES ('น่าน', 'Nan', 'North', 'สันติสุข', 'Santi Suk');
INSERT INTO amphur VALUES ('บึงกาฬ', 'Bueng Kan', 'North-East', 'เซกา', 'Seka');
INSERT INTO amphur VALUES ('บึงกาฬ', 'Bueng Kan', 'North-East', 'โซ่พิสัย', 'So Phisai');
INSERT INTO amphur VALUES ('บึงกาฬ', 'Bueng Kan', 'North-East', 'บึงโขงหลง', 'Bueng Khong Long');
INSERT INTO amphur VALUES ('บึงกาฬ', 'Bueng Kan', 'North-East', 'บุ่งคล้า', 'Bung Khla');
INSERT INTO amphur VALUES ('บึงกาฬ', 'Bueng Kan', 'North-East', 'ปากคาด', 'Pak Khat');
INSERT INTO amphur VALUES ('บึงกาฬ', 'Bueng Kan', 'North-East', 'พรเจริญ', 'Phon Charoen');
INSERT INTO amphur VALUES ('บึงกาฬ', 'Bueng Kan', 'North-East', 'เมืองบึงกาฬ', 'Mueang Bueng Kan');
INSERT INTO amphur VALUES ('บึงกาฬ', 'Bueng Kan', 'North-East', 'ศรีวิไล', 'Si Wilai');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'กระสัง', 'Krasang');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'คูเมือง', 'Khu Mueang');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'แคนดง', 'Khaen Dong');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'ชำนิ', 'Chamni');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'นางรอง', 'Nang Rong');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'นาโพธิ์', 'Na Pho');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'โนนดินแดง', 'Non Din Daeng');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'โนนสุวรรณ', 'Non Suwan');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'บ้านกรวด', 'Ban Kruat');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'บ้านด่าน', 'Ban Dan');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'บ้านใหม่ไชยพจน์', 'Ban Mai Chaiyaphot');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'ประโคนชัย', 'Prakhon Chai');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'ปะคำ', 'Pakham');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'พลับพลาชัย', 'Phlapphla Chai');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'พุทไธสง', 'Phutthaisong');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'เมืองบุรีรัมย์', 'Mueang Buriram');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'ละหานทราย', 'Lahan Sai');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'ลำปลายมาศ', 'Lam Plai Mat');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'สตึก', 'Satuek');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'หนองกี่', 'Nong Ki');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'หนองหงส์', 'Nong Hong');
INSERT INTO amphur VALUES ('บุรีรัมย์', 'Buriram', 'North-East', 'ห้วยราช', 'Huai Rat');
INSERT INTO amphur VALUES ('ปทุมธานี', 'Pathum Thani', 'Centre', 'คลองหลวง', 'Khlong Luang');
INSERT INTO amphur VALUES ('ปทุมธานี', 'Pathum Thani', 'Centre', 'ธัญบุรี', 'Thanyaburi');
INSERT INTO amphur VALUES ('ปทุมธานี', 'Pathum Thani', 'Centre', 'เมืองปทุมธานี', 'Mueang Pathum Thani');
INSERT INTO amphur VALUES ('ปทุมธานี', 'Pathum Thani', 'Centre', 'ลาดหลุมแก้ว', 'Lat Lum Kaeo');
INSERT INTO amphur VALUES ('ปทุมธานี', 'Pathum Thani', 'Centre', 'ลำลูกกา', 'Lam Luk Ka');
INSERT INTO amphur VALUES ('ปทุมธานี', 'Pathum Thani', 'Centre', 'สามโคก', 'Sam Khok');
INSERT INTO amphur VALUES ('ปทุมธานี', 'Pathum Thani', 'Centre', 'หนองเสือ', 'Nong Suea');
INSERT INTO amphur VALUES ('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'West', 'กุยบุรี', 'Kui Buri');
INSERT INTO amphur VALUES ('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'West', 'ทับสะแก', 'Thap Sakae');
INSERT INTO amphur VALUES ('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'West', 'บางสะพาน', 'Bang Saphan');
INSERT INTO amphur VALUES ('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'West', 'บางสะพานน้อย', 'Bang Saphan Noi');
INSERT INTO amphur VALUES ('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'West', 'ปราณบุรี', 'Pran Buri');
INSERT INTO amphur VALUES ('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'West', 'เมืองประจวบคีรีขันธ์', 'Mueang Prachuap Khiri Khan');
INSERT INTO amphur VALUES ('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'West', 'สามร้อยยอด', 'Sam Roi Yot');
INSERT INTO amphur VALUES ('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'West', 'หัวหิน', 'Hua Hin');
INSERT INTO amphur VALUES ('ปราจีนบุรี', 'Prachin Buri', 'East', 'กบินทร์บุรี', 'Kabin Buri');
INSERT INTO amphur VALUES ('ปราจีนบุรี', 'Prachin Buri', 'East', 'นาดี', 'Na Di');
INSERT INTO amphur VALUES ('ปราจีนบุรี', 'Prachin Buri', 'East', 'บ้านสร้าง', 'Ban Sang');
INSERT INTO amphur VALUES ('ปราจีนบุรี', 'Prachin Buri', 'East', 'ประจันตคาม', 'Prachantakham');
INSERT INTO amphur VALUES ('ปราจีนบุรี', 'Prachin Buri', 'East', 'เมืองปราจีนบุรี', 'Mueang Prachinburi');
INSERT INTO amphur VALUES ('ปราจีนบุรี', 'Prachin Buri', 'East', 'ศรีมหาโพธิ', 'Si Maha Phot');
INSERT INTO amphur VALUES ('ปราจีนบุรี', 'Prachin Buri', 'East', 'ศรีมโหสถ', 'Si Mahosot');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'กะพ้อ', 'Kapho');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'โคกโพธิ์', 'Khok Pho');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'ทุ่งยางแดง', 'Thung Yang Daeng');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'ปะนาเระ', 'Panare');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'มายอ', 'Mayo');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'เมืองปัตตานี', 'Mueang Pattani');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'แม่ลาน', 'Mae Lan');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'ไม้แก่น', 'Mai Kaen');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'ยะรัง', 'Yarang');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'ยะหริ่ง', 'Yaring');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'สายบุรี', 'Sai Buri');
INSERT INTO amphur VALUES ('ปัตตานี', 'Pattani', 'South', 'หนองจิก', 'Nong Chik');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'ท่าเรือ', 'Tha Ruea');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'นครหลวง', 'Nakhon Luang');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'บางซ้าย', 'Bang Sai 1413');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'บางไทร', 'Bang Sai 1404');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'บางบาล', 'Bang Ban');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'บางปะหัน', 'Bang Pahan');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'บางปะอิน', 'Bang Pa In');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'บ้านแพรก', 'Ban Phraek');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'ผักไห่', 'Phak Hai');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'ภาชี', 'Phachi');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'มหาราช', 'Maha Rat');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'ลาดบัวหลวง', 'Lat Bua Luang');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'วังน้อย', 'Wang Noi');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'เสนา', 'Sena');
INSERT INTO amphur VALUES ('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Centre', 'อุทัย', 'Uthai');
INSERT INTO amphur VALUES ('พะเยา', 'Phayao', 'North', 'จุน', 'Chun');
INSERT INTO amphur VALUES ('พะเยา', 'Phayao', 'North', 'เชียงคำ', 'Chiang Kham');
INSERT INTO amphur VALUES ('พะเยา', 'Phayao', 'North', 'เชียงม่วน', 'Chiang Muan');
INSERT INTO amphur VALUES ('พะเยา', 'Phayao', 'North', 'ดอกคำใต้', 'Dok Khamtai');
INSERT INTO amphur VALUES ('พะเยา', 'Phayao', 'North', 'ปง', 'Pong');
INSERT INTO amphur VALUES ('พะเยา', 'Phayao', 'North', 'ภูกามยาว', 'Phu Kamyao');
INSERT INTO amphur VALUES ('พะเยา', 'Phayao', 'North', 'ภูซาง', 'Phu Sang');
INSERT INTO amphur VALUES ('พะเยา', 'Phayao', 'North', 'เมืองพะเยา', 'Mueang Phayao');
INSERT INTO amphur VALUES ('พะเยา', 'Phayao', 'North', 'แม่ใจ', 'Mae Chai');
INSERT INTO amphur VALUES ('พังงา', 'Phang Nga', 'South', 'กะปง', 'Kapong');
INSERT INTO amphur VALUES ('พังงา', 'Phang Nga', 'South', 'เกาะยาว', 'Ko Yao');
INSERT INTO amphur VALUES ('พังงา', 'Phang Nga', 'South', 'คุระบุรี', 'Khura Buri');
INSERT INTO amphur VALUES ('พังงา', 'Phang Nga', 'South', 'ตะกั่วทุ่ง', 'Takua Thung');
INSERT INTO amphur VALUES ('พังงา', 'Phang Nga', 'South', 'ตะกั่วป่า', 'Takua Pa');
INSERT INTO amphur VALUES ('พังงา', 'Phang Nga', 'South', 'ทับปุด', 'Thap Put');
INSERT INTO amphur VALUES ('พังงา', 'Phang Nga', 'South', 'ท้ายเหมือง', 'Thai Mueang');
INSERT INTO amphur VALUES ('พังงา', 'Phang Nga', 'South', 'เมืองพังงา', 'Mueang Phang Nga');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'กงหรา', 'Kong Ra');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'เขาชัยสน', 'Khao Chaison');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'ควนขนุน', 'Khuan Khanun');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'ตะโหมด', 'Tamot');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'บางแก้ว', 'Bang Kaeo');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'ปากพะยูน', 'Pak Phayun');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'ป่าบอน', 'Pa Bon');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'ป่าพะยอม', 'Pa Phayom');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'เมืองพัทลุง', 'Mueang Phatthalung');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'ศรีนครินทร์', 'Srinagarindra');
INSERT INTO amphur VALUES ('พัทลุง', 'Phatthalung', 'South', 'ศรีบรรพต', 'Si Banphot');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'ดงเจริญ', 'Dong Charoen');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'ตะพานหิน', 'Taphan Hin');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'ทับคล้อ', 'Thap Khlo');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'บางมูลนาก', 'Bang Mun Nak');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'บึงนาราง', 'Bueng Na Rang');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'โพทะเล', 'Pho Thale');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'โพธิ์ประทับช้าง', 'Pho Prathap Chang');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'เมืองอุทัยธานี', 'Mueang Phichit');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'วชิรบารมี', 'Wachirabarami');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'วังทรายพูน', 'Wang Sai Phun');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'สากเหล็ก', 'Sak Lek');
INSERT INTO amphur VALUES ('พิจิตร', 'Phichit', 'Centre', 'สามง่าม', 'Sam Ngam');
INSERT INTO amphur VALUES ('พิษณุโลก', 'Phitsanulok', 'Centre', 'ชาติตระการ', 'Chat Trakan');
INSERT INTO amphur VALUES ('พิษณุโลก', 'Phitsanulok', 'Centre', 'นครไทย', 'Nakhon Thai');
INSERT INTO amphur VALUES ('พิษณุโลก', 'Phitsanulok', 'Centre', 'เนินมะปราง', 'Noen Maprang');
INSERT INTO amphur VALUES ('พิษณุโลก', 'Phitsanulok', 'Centre', 'บางกระทุ่ม', 'Bang Krathum');
INSERT INTO amphur VALUES ('พิษณุโลก', 'Phitsanulok', 'Centre', 'บางระกำ', 'Bang Rakam');
INSERT INTO amphur VALUES ('พิษณุโลก', 'Phitsanulok', 'Centre', 'พรหมพิราม', 'Phrom Phiram');
INSERT INTO amphur VALUES ('พิษณุโลก', 'Phitsanulok', 'Centre', 'เมืองพิษณุโลก', 'Mueang Phitsanulok');
INSERT INTO amphur VALUES ('พิษณุโลก', 'Phitsanulok', 'Centre', 'วังทอง', 'Wang Thong');
INSERT INTO amphur VALUES ('พิษณุโลก', 'Phitsanulok', 'Centre', 'วัดโบสถ์', 'Wat Bot');
INSERT INTO amphur VALUES ('เพชรบุรี', 'Phetchaburi', 'West', 'แก่งกระจาน', 'Kaeng Krachan');
INSERT INTO amphur VALUES ('เพชรบุรี', 'Phetchaburi', 'West', 'เขาย้อย', 'Khao Yoi');
INSERT INTO amphur VALUES ('เพชรบุรี', 'Phetchaburi', 'West', 'ชะอำ', 'Cha-am');
INSERT INTO amphur VALUES ('เพชรบุรี', 'Phetchaburi', 'West', 'ท่ายาง', 'Tha Yang');
INSERT INTO amphur VALUES ('เพชรบุรี', 'Phetchaburi', 'West', 'บ้านลาด', 'Ban Lat');
INSERT INTO amphur VALUES ('เพชรบุรี', 'Phetchaburi', 'West', 'บ้านแหลม', 'Ban Laem');
INSERT INTO amphur VALUES ('เพชรบุรี', 'Phetchaburi', 'West', 'เมืองเพชรบุรี', 'Mueang Phetchaburi');
INSERT INTO amphur VALUES ('เพชรบุรี', 'Phetchaburi', 'West', 'หนองหญ้าปล้อง', 'Nong Ya Plong');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'เขาค้อ', 'Khao Kho');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'ชนแดน', 'Chon Daen');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'น้ำหนาว', 'Nam Nao');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'บึงสามพัน', 'Bueng Sam Phan');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'เมืองเพชรบูรณ์', 'Mueang Phetchabun');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'วังโป่ง', 'Wang Pong');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'วิเชียรบุรี', 'Wichian Buri');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'ศรีเทพ', 'Si Thep');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'หนองไผ่', 'Nong Phai');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'หล่มเก่า', 'Lom Kao');
INSERT INTO amphur VALUES ('เพชรบูรณ์', 'Phetchabun', 'Centre', 'หล่มสัก', 'Lom Sak');
INSERT INTO amphur VALUES ('แพร่', 'Phrae', 'North', 'เด่นชัย', 'Den Chai');
INSERT INTO amphur VALUES ('แพร่', 'Phrae', 'North', 'เมืองแพร่', 'Mueang Phrae');
INSERT INTO amphur VALUES ('แพร่', 'Phrae', 'North', 'ร้องกวาง', 'Rong Kwang');
INSERT INTO amphur VALUES ('แพร่', 'Phrae', 'North', 'ลอง', 'Long');
INSERT INTO amphur VALUES ('แพร่', 'Phrae', 'North', 'วังชิ้น', 'Wang Chin');
INSERT INTO amphur VALUES ('แพร่', 'Phrae', 'North', 'สอง', 'Song');
INSERT INTO amphur VALUES ('แพร่', 'Phrae', 'North', 'สูงเม่น', 'Sung Men');
INSERT INTO amphur VALUES ('แพร่', 'Phrae', 'North', 'หนองม่วงไข่', 'Nong Muang Khai');
INSERT INTO amphur VALUES ('ภูเก็ต', 'Phuket', 'South', 'กะทู้', 'Kathu');
INSERT INTO amphur VALUES ('ภูเก็ต', 'Phuket', 'South', 'ถลาง', 'Thalang');
INSERT INTO amphur VALUES ('ภูเก็ต', 'Phuket', 'South', 'เมืองภูเก็ต', 'Mueang Phuket');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'กันทรวิชัย', 'Kantharawichai');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'กุดรัง', 'Kut Rang');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'แกดำ', 'Kae Dam');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'โกสุมพิสัย', 'Kosum Phisai');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'ชื่นชม', 'Chuen Chom');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'เชียงยืน', 'Chiang Yuen');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'นาเชือก', 'Na Chueak');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'นาดูน', 'Na Dun');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'บรบือ', 'Borabue');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'พยัคฆภูมิพิสัย', 'Phayakkhaphum Phisai');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'เมืองมหาสารคาม', 'Mueang Maha Sarakham');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'ยางสีสุราช', 'Yang Sisurat');
INSERT INTO amphur VALUES ('มหาสารคาม', 'Maha Sarakham', 'North-East', 'วาปีปทุม', 'Wapi Pathum');
INSERT INTO amphur VALUES ('มุกดาหาร', 'Mukdahan', 'North-East', 'คำชะอี', 'Khamcha-i');
INSERT INTO amphur VALUES ('มุกดาหาร', 'Mukdahan', 'North-East', 'ดงหลวง', 'Dong Luang');
INSERT INTO amphur VALUES ('มุกดาหาร', 'Mukdahan', 'North-East', 'ดอนตาล', 'Don Tan');
INSERT INTO amphur VALUES ('มุกดาหาร', 'Mukdahan', 'North-East', 'นิคมคำสร้อย', 'Nikhom Kham Soi');
INSERT INTO amphur VALUES ('มุกดาหาร', 'Mukdahan', 'North-East', 'เมืองมุกดาหาร', 'Mueang Mukdahan');
INSERT INTO amphur VALUES ('มุกดาหาร', 'Mukdahan', 'North-East', 'หนองสูง', 'Nong Sung');
INSERT INTO amphur VALUES ('มุกดาหาร', 'Mukdahan', 'North-East', 'หว้านใหญ่', 'Wan Yai');
INSERT INTO amphur VALUES ('แม่ฮ่องสอน', 'Mae Hong Son', 'North', 'ขุนยวม', 'Khun Yuam');
INSERT INTO amphur VALUES ('แม่ฮ่องสอน', 'Mae Hong Son', 'North', 'ปางมะผ้า', 'Pang Mapha');
INSERT INTO amphur VALUES ('แม่ฮ่องสอน', 'Mae Hong Son', 'North', 'ปาย', 'Pai');
INSERT INTO amphur VALUES ('แม่ฮ่องสอน', 'Mae Hong Son', 'North', 'เมืองแม่ฮ่องสอน', 'Mueang Mae Hong Son');
INSERT INTO amphur VALUES ('แม่ฮ่องสอน', 'Mae Hong Son', 'North', 'แม่ลาน้อย', 'Mae La Noi');
INSERT INTO amphur VALUES ('แม่ฮ่องสอน', 'Mae Hong Son', 'North', 'แม่สะเรียง', 'Mae Sariang');
INSERT INTO amphur VALUES ('แม่ฮ่องสอน', 'Mae Hong Son', 'North', 'สบเมย', 'Sop Moei');
INSERT INTO amphur VALUES ('ยโสธร', 'Yasothon', 'North-East', 'กุดชุม', 'Kut Chum');
INSERT INTO amphur VALUES ('ยโสธร', 'Yasothon', 'North-East', 'ค้อวัง', 'Kho Wang');
INSERT INTO amphur VALUES ('ยโสธร', 'Yasothon', 'North-East', 'คำเขื่อนแก้ว', 'Kham Khuean Kaeo');
INSERT INTO amphur VALUES ('ยโสธร', 'Yasothon', 'North-East', 'ทรายมูล', 'Sai Mun');
INSERT INTO amphur VALUES ('ยโสธร', 'Yasothon', 'North-East', 'ไทยเจริญ', 'Thai Charoen');
INSERT INTO amphur VALUES ('ยโสธร', 'Yasothon', 'North-East', 'ป่าติ้ว', 'Pa Tio');
INSERT INTO amphur VALUES ('ลำพูน', 'Lamphun', 'North', 'ป่าซาง', 'Pa Sang');
INSERT INTO amphur VALUES ('ยโสธร', 'Yasothon', 'North-East', 'มหาชนะชัย', 'Maha Chana Chai');
INSERT INTO amphur VALUES ('ยโสธร', 'Yasothon', 'North-East', 'เมืองยโสธร', 'Mueang Yasothon');
INSERT INTO amphur VALUES ('ยโสธร', 'Yasothon', 'North-East', 'เลิงนกทา', 'Loeng Nok Tha');
INSERT INTO amphur VALUES ('ยะลา', 'Yala', 'South', 'กรงปินัง', 'Krong Pinang');
INSERT INTO amphur VALUES ('ยะลา', 'Yala', 'South', 'กาบัง', 'Kabang');
INSERT INTO amphur VALUES ('ยะลา', 'Yala', 'South', 'ธารโต', 'Than To');
INSERT INTO amphur VALUES ('ยะลา', 'Yala', 'South', 'บันนังสตา', 'Bannang Sata');
INSERT INTO amphur VALUES ('ยะลา', 'Yala', 'South', 'เบตง', 'Betong');
INSERT INTO amphur VALUES ('ยะลา', 'Yala', 'South', 'เมืองยะลา', 'Mueang Yala');
INSERT INTO amphur VALUES ('ยะลา', 'Yala', 'South', 'ยะหา', 'Yaha');
INSERT INTO amphur VALUES ('ยะลา', 'Yala', 'South', 'รามัน', 'Raman');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'เกษตรวิสัย', 'Kaset Wisai');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'จตุรพักตรพิมาน', 'Chaturaphak Phiman');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'จังหาร', 'Changhan');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'เชียงขวัญ', 'Chiang Khwan');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'ทุ่งเขาหลวง', 'Thung Khao Luang');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'ธวัชบุรี', 'Thawat Buri');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'ปทุมรัตต์', 'Pathum Rat');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'พนมไพร', 'Phanom Phrai');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'โพธิ์ชัย', 'Pho Chai');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'โพนทราย', 'Phon Sai');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'โพนทอง', 'Phon Thong');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'เมยวดี', 'Moei Wadi');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'เมืองร้อยเอ็ด', 'Mueang Roi Et');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'เมืองสรวง', 'Mueang Suang');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'ศรีสมเด็จ', 'Si Somdet');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'สุวรรณภูมิ', 'Suwannaphum');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'เสลภูมิ', 'Selaphum');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'หนองพอก', 'Nong Phok');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'หนองฮี', 'Nong Hi');
INSERT INTO amphur VALUES ('ร้อยเอ็ด', 'Roi Et', 'North-East', 'อาจสามารถ', 'At Samat');
INSERT INTO amphur VALUES ('ระนอง', 'Ranong', 'South', 'กระบุรี', 'Kra Buri');
INSERT INTO amphur VALUES ('ระนอง', 'Ranong', 'South', 'กะเปอร์', 'Kapoe');
INSERT INTO amphur VALUES ('ระนอง', 'Ranong', 'South', 'เมืองระนอง', 'Mueang Ranong');
INSERT INTO amphur VALUES ('ระนอง', 'Ranong', 'South', 'ละอุ่น', 'La-un');
INSERT INTO amphur VALUES ('ระนอง', 'Ranong', 'South', 'สุขสำราญ', 'Suk Samran');
INSERT INTO amphur VALUES ('ระยอง', 'Rayong', 'East', 'แกลง', 'Klaeng');
INSERT INTO amphur VALUES ('ระยอง', 'Rayong', 'East', 'เขาชะเมา', 'Khao Chamao');
INSERT INTO amphur VALUES ('ระยอง', 'Rayong', 'East', 'นิคมพัฒนา', 'Nikhom Phatthana');
INSERT INTO amphur VALUES ('ระยอง', 'Rayong', 'East', 'บ้านค่าย', 'Ban Khai');
INSERT INTO amphur VALUES ('ระยอง', 'Rayong', 'East', 'บ้านฉาง', 'Ban Chang');
INSERT INTO amphur VALUES ('ระยอง', 'Rayong', 'East', 'ปลวกแดง', 'Pluak Daeng');
INSERT INTO amphur VALUES ('ระยอง', 'Rayong', 'East', 'เมืองระยอง', 'Mueang Rayong');
INSERT INTO amphur VALUES ('ระยอง', 'Rayong', 'East', 'วังจันทร์', 'Wang Chan');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'จอมบึง', 'Chom Bueng');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'ดำเนินสะดวก', 'Damnoen Saduak');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'บางแพ', 'Bang Phae');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'บ้านคา', 'Ban Kha');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'บ้านโป่ง', 'Ban Pong');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'ปากท่อ', 'Pak Tho');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'โพธาราม', 'Photharam');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'เมืองราชบุรี', 'Mueang Ratchaburi');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'วัดเพลง', 'Wat Phleng');
INSERT INTO amphur VALUES ('ราชบุรี', 'Ratchaburi', 'West', 'สวนผึ้ง', 'Suan Phueng');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'โคกเจริญ', 'Khok Charoen');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'โคกสำโรง', 'Khok Samrong');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'ชัยบาดาล', 'Chai Badan');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'ท่าวุ้ง', 'Tha Wung');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'ท่าหลวง', 'Tha Luang');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'บ้านหมี่', 'Ban Mi');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'พัฒนานิคม', 'Phatthana Nikhom');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'เมืองลพบุรี', 'Mueang Lopburi');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'ลำสนธิ', 'Lam Sonthi');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'สระโบสถ์', 'Sa Bot');
INSERT INTO amphur VALUES ('ลพบุรี', 'Lopburi', 'Centre', 'หนองม่วง', 'Nong Muang');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'เกาะคา', 'Ko Kha');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'งาว', 'Ngao');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'แจ้ห่ม', 'Chae Hom');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'เถิน', 'Thoen');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'เมืองปาน', 'Mueang Pan');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'เมืองลำปาง', 'Mueang Lampang');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'แม่ทะ', 'Mae Tha Lampang');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'แม่เมาะ', 'Mae Mo');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'แม่ริม', 'Mae Phrik');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'วังเหนือ', 'Wang Nuea');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'สบปราบ', 'Sop Prap');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'เสริมงาม', 'Soem Ngam');
INSERT INTO amphur VALUES ('ลำปาง', 'Lampang', 'North', 'ห้างฉัตร', 'Hang Chat');
INSERT INTO amphur VALUES ('ลำพูน', 'Lamphun', 'North', 'ทุ่งหัวช้าง', 'Thung Hua Chang');
INSERT INTO amphur VALUES ('ลำพูน', 'Lamphun', 'North', 'บ้านธิ', 'Ban Thi');
INSERT INTO amphur VALUES ('ลำพูน', 'Lamphun', 'North', 'บ้านโฮ่ง', 'Ban Hong');
INSERT INTO amphur VALUES ('ลำพูน', 'Lamphun', 'North', 'เมืองลำพูน', 'Mueang Lamphun');
INSERT INTO amphur VALUES ('ลำพูน', 'Lamphun', 'North', 'แม่ทา', 'Mae Tha, Lamphun');
INSERT INTO amphur VALUES ('ลำพูน', 'Lamphun', 'North', 'ลี้', 'Li');
INSERT INTO amphur VALUES ('ลำพูน', 'Lamphun', 'North', 'เวียงหนองล่อง', 'Wiang Nong Long');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'เชียงคาน', 'Chiang Khan');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'ด่านซ้าย', 'Dan Sai');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'ท่าลี่', 'Tha Li');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'นาด้วง', 'Na Duang');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'นาแห้ว', 'Na Haeo');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'ปากชม', 'Pak Chom');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'ผาขาว', 'Pha Khao');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'ภูกระดึง', 'Phu Kradueng');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'ภูเรือ', 'Phu Ruea');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'ภูหลวง', 'Phu Luang');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'เมืองเลย', 'Mueang Loei');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'วังสะพุง', 'Wang Saphung');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'หนองหิน', 'Nong Hin');
INSERT INTO amphur VALUES ('เลย', 'Loei', 'North-East', 'เอราวัณ', 'Erawan');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'กันทรลักษ์', 'Kantharalak');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'กันทรารมย์', 'Kanthararom');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ขุขันธ์', 'Khukhan');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ขุนหาญ', 'Khun Han');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'น้ำเกลี้ยง', 'Nam Kliang');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'โนนคูน', 'Non Khun');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'บึงบูรพ์', 'Bueng Bun');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'เบญจลักษ์', 'Benchalak');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ปรางค์กู่', 'Prang Ku');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'พยุห์', 'Phayu');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'โพธิ์ศรีสุวรรณ', 'Pho Si Suwan');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ไพรบึง', 'Phrai Bueng');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ภูสิงห์', 'Phu Sing');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'เมืองจันทร์', 'Mueang Chan');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'เมืองศรีสะเกษ', 'Mueang Sisaket');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ยางชุมน้อย', 'Yang Chum Noi');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ราษีไศล', 'Rasi Salai');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'วังหิน', 'Wang Hin');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ศรีรัตนะ', 'Si Rattana');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ศิลาลาด', 'Sila Lat');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'ห้วยทับทัน', 'Huai Thap Than');
INSERT INTO amphur VALUES ('ศรีสะเกษ', 'Sisaket', 'North-East', 'อุทุมพรพิสัย', 'Uthumphon Phisai');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'กุดบาก', 'Kut Bak');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'กุสุมาลย์', 'Kusuman');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'คำตากล้า', 'Kham Ta Kla');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'โคกศรีสุพรรณ', 'Khok Si Suphan');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'เจริญศิลป์', 'Charoen Sin');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'เต่างอย', 'Tao Ngoi');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'นิคมน้ำอูน', 'Nikhom Nam Un');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'บ้านม่วง', 'Ban Muang');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'พรรณนานิคม', 'Phanna Nikhom');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'พังโคน', 'Phang Khon');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'โพนนาแก้ว', 'Phon Na Kaeo');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'ภูพาน', 'Phu Phan');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'เมืองสกลนคร', 'Mueang Sakon Nakhon');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'วานรนิวาส', 'Wanon Niwat');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'วาริชภูมิ', 'Waritchaphum');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'สว่างแดนดิน', 'Sawang Daen Din');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'ส่องดาว', 'Song Dao');
INSERT INTO amphur VALUES ('สกลนคร', 'Sakon Nakhon', 'North-East', 'อากาศอำนวย', 'Akat Amnuai');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'กระแสสินธุ์', 'Krasae Sin');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'คลองหอยโข่ง', 'Khlong Hoi Khong');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'ควนเนียง', 'Khuan Niang');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'จะนะ', 'Chana');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'เทพา', 'Thepha');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'นาทวี', 'Na Thawi');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'นาหม่อม', 'Na Mom');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'บางกล่ำ', 'Bang Klam');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'เมืองสงขลา', 'Mueang Songkhla');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'ระโนด', 'Ranot');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'รัตภูมิ', 'Rattaphum');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'สทิงพระ', 'Sathing Phra');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'สะเดา', 'Sadao');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'สะบ้าย้อย', 'Saba Yoi');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'สิงหนคร', 'Singhanakhon');
INSERT INTO amphur VALUES ('สงขลา', 'Songkhla', 'South', 'หาดใหญ่', 'Hat Yai');
INSERT INTO amphur VALUES ('สตูล', 'Satun', 'South', 'ควนกาหลง', 'Khuan Kalong');
INSERT INTO amphur VALUES ('สตูล', 'Satun', 'South', 'ควนโดน', 'Khuan Don');
INSERT INTO amphur VALUES ('สตูล', 'Satun', 'South', 'ท่าแพ', 'Tha Phae');
INSERT INTO amphur VALUES ('สตูล', 'Satun', 'South', 'ทุ่งหว้า', 'Thung Wa');
INSERT INTO amphur VALUES ('สตูล', 'Satun', 'South', 'มะนัง', 'Manang');
INSERT INTO amphur VALUES ('สตูล', 'Satun', 'South', 'เมืองสตูล', 'Mueang Satun');
INSERT INTO amphur VALUES ('สตูล', 'Satun', 'South', 'ละงู', 'La-ngu');
INSERT INTO amphur VALUES ('สมุทรปราการ', 'Samut Prakan', 'Centre', 'บางบ่อ', 'Bang Bo');
INSERT INTO amphur VALUES ('สมุทรปราการ', 'Samut Prakan', 'Centre', 'บางพลี', 'Bang Phli');
INSERT INTO amphur VALUES ('สมุทรปราการ', 'Samut Prakan', 'Centre', 'บางเสาธง', 'Bang Sao Thong');
INSERT INTO amphur VALUES ('สมุทรปราการ', 'Samut Prakan', 'Centre', 'พระประแดง', 'Phra Pradaeng');
INSERT INTO amphur VALUES ('สมุทรปราการ', 'Samut Prakan', 'Centre', 'พระสมุทรเจดีย์', 'Phra Samut Chedi');
INSERT INTO amphur VALUES ('สมุทรปราการ', 'Samut Prakan', 'Centre', 'เมืองสมุทรปราการ', 'Mueang Samut Prakan');
INSERT INTO amphur VALUES ('สมุทรสงคราม', 'Samut Songkhram', 'Centre', 'บางคนที', 'Bang Khonthi');
INSERT INTO amphur VALUES ('สมุทรสงคราม', 'Samut Songkhram', 'Centre', 'เมืองสมุทรสงคราม', 'Mueang Samut Songkhram');
INSERT INTO amphur VALUES ('สมุทรสงคราม', 'Samut Songkhram', 'Centre', 'อัมพวา', 'Amphawa');
INSERT INTO amphur VALUES ('สมุทรสาคร', 'Samut Sakhon', 'Centre', 'กระทุ่มแบน', 'Krathum Baen');
INSERT INTO amphur VALUES ('สมุทรสาคร', 'Samut Sakhon', 'Centre', 'บ้านแพ้ว', 'Ban Phaeo');
INSERT INTO amphur VALUES ('สมุทรสาคร', 'Samut Sakhon', 'Centre', 'เมืองสมุทรสาคร', 'Mueang Samut Sakhon');
INSERT INTO amphur VALUES ('สระแก้ว', 'Sa Kaeo', 'East', 'เขาฉกรรจ์', 'Khao Chakan');
INSERT INTO amphur VALUES ('สระแก้ว', 'Sa Kaeo', 'East', 'คลองหาด', 'Khlong Hat');
INSERT INTO amphur VALUES ('สระแก้ว', 'Sa Kaeo', 'East', 'โคกสูง', 'Khok Sung');
INSERT INTO amphur VALUES ('สระแก้ว', 'Sa Kaeo', 'East', 'ตาพระยา', 'Ta Phraya');
INSERT INTO amphur VALUES ('สระแก้ว', 'Sa Kaeo', 'East', 'เมืองสระแก้ว', 'Mueang Sa Kaeo');
INSERT INTO amphur VALUES ('สระแก้ว', 'Sa Kaeo', 'East', 'วังน้ำเย็น', 'Wang Nam Yen');
INSERT INTO amphur VALUES ('สระแก้ว', 'Sa Kaeo', 'East', 'วังสมบูรณ์', 'Wang Sombun');
INSERT INTO amphur VALUES ('สระแก้ว', 'Sa Kaeo', 'East', 'วัฒนานคร', 'Watthana Nakhon');
INSERT INTO amphur VALUES ('สระแก้ว', 'Sa Kaeo', 'East', 'อรัญประเทศ', 'Aranyaprathet');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'แก่งคอย', 'Kaeng Khoi');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'เฉลิมพระเกียรติ', 'Chaloem Phra Kiat');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'ดอนพุด', 'Don Phut');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'บ้านหมอ', 'Ban Mo');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'พระพุทธบาท', 'Phra Phutthabat');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'มวกเหล็ก', 'Muak Lek');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'เมืองสระบุรี', 'Mueang Saraburi');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'วังม่วง', 'Wang Muang');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'วิหารแดง', 'Wihan Daeng');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'เสาไห้', 'Sao Hai');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'หนองแค', 'Nong Khae');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'หนองแซง', 'Nong Saeng');
INSERT INTO amphur VALUES ('สระบุรี', 'Saraburi', 'Centre', 'หนองโดน', 'Nong Don');
INSERT INTO amphur VALUES ('สิงห์บุรี', 'Sing Buri', 'Centre', 'ค่ายบางระจัน', 'Khai Bang Rachan');
INSERT INTO amphur VALUES ('สิงห์บุรี', 'Sing Buri', 'Centre', 'ท่าช้าง', 'Tha Chang');
INSERT INTO amphur VALUES ('สิงห์บุรี', 'Sing Buri', 'Centre', 'บางระจัน', 'Bang Rachan');
INSERT INTO amphur VALUES ('สิงห์บุรี', 'Sing Buri', 'Centre', 'พรหมบุรี', 'Phrom Buri');
INSERT INTO amphur VALUES ('สิงห์บุรี', 'Sing Buri', 'Centre', 'เมืองสิงห์บุรี', 'Mueang Sing Buri');
INSERT INTO amphur VALUES ('สิงห์บุรี', 'Sing Buri', 'Centre', 'อินทร์บุรี', 'In Buri');
INSERT INTO amphur VALUES ('สุโขทัย', 'Sukhothai', 'Centre', 'กงไกรลาศ', 'Kong Krailat');
INSERT INTO amphur VALUES ('สุโขทัย', 'Sukhothai', 'Centre', 'คีรีมาศ', 'Khiri Mat');
INSERT INTO amphur VALUES ('สุโขทัย', 'Sukhothai', 'Centre', 'ทุ่งเสลี่ยม', 'Thung Saliam');
INSERT INTO amphur VALUES ('สุโขทัย', 'Sukhothai', 'Centre', 'บ้านด่านลานหอย', 'Ban Dan Lan Hoi');
INSERT INTO amphur VALUES ('สุโขทัย', 'Sukhothai', 'Centre', 'เมืองสุโขทัย', 'Mueang Sukhothai');
INSERT INTO amphur VALUES ('สุโขทัย', 'Sukhothai', 'Centre', 'ศรีนคร', 'Si Nakhon');
INSERT INTO amphur VALUES ('สุโขทัย', 'Sukhothai', 'Centre', 'ศรีสัชนาลัย', 'Si Satchanalai');
INSERT INTO amphur VALUES ('สุโขทัย', 'Sukhothai', 'Centre', 'ศรีสำโรง', 'Si Samrong');
INSERT INTO amphur VALUES ('สุโขทัย', 'Sukhothai', 'Centre', 'สวรรคโลก', 'Sawankhalok');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'ดอนเจดีย์', 'Don Chedi');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'ด่านช้าง', 'Dan Chang');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'เดิมบางนางบวช', 'Doem Bang Nang Buat');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'บางปลาม้า', 'Bang Pla Ma');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'เมืองสุพรรณบุรี', 'Mueang Suphanburi');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'ศรีประจันต์', 'Si Prachan');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'สองพี่น้อง', 'Song Phi Nong');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'สามชุก', 'Sam Chuk');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'หนองหญ้าไซ', 'Nong Ya Sai');
INSERT INTO amphur VALUES ('สุพรรณบุรี', 'Suphan Buri', 'Centre', 'อู่ทอง', 'U Thong');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'กาญจนดิษฐ์', 'Kanchanadit');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'เกาะพะงัน', 'Ko Pha-ngan');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'เกาะสมุย', 'Ko Samui');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'คีรีรัฐนิคม', 'Khiri Rat Nikhom');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'เคียนซา', 'Khian Sa');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'ชัยบุรี', 'Chai Buri');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'ไชยา', 'Chaiya');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'ดอนสัก', 'Don Sak');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'ท่าฉาง', 'Tha Chang');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'ท่าชนะ', 'Tha Chana');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'บ้านตาขุน', 'Ban Ta Khun');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'บ้านนาเดิม', 'Ban Na Doem');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'บ้านนาสาร', 'Ban Na San');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'พนม', 'Phanom');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'พระแสง', 'Phrasaeng');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'พุนพิน', 'Phunphin');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'เมืองสุราษฎร์ธานี', 'Mueang Surat Thani');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'วิภาวดี', 'Vibhavadi');
INSERT INTO amphur VALUES ('สุราษฎร์ธานี', 'Surat Thani', 'South', 'เวียงสระ', 'Wiang Sa');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'กาบเชิง', 'Kap Choeng');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'เขวาสินรินทร์', 'Khwao Sinarin');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'จอมพระ', 'Chom Phra');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'ชุมพลบุรี', 'Chumphon Buri');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'ท่าตูม', 'Tha Tum');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'โนนนารายณ์', 'Non Narai');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'บัวเชด', 'Buachet');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'ปราสาท', 'Prasat');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'พนมดงรัก', 'Phanom Dong Rak');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'เมืองสุรินทร์', 'Mueang Surin');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'รัตนบุรี', 'Rattanaburi');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'ลำดวน', 'Lamduan');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'ศรีณรงค์', 'Si Narong');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'ศีขรภูมิ', 'Sikhoraphum');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'สนม', 'Sanom');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'สังขะ', 'Sangkha');
INSERT INTO amphur VALUES ('สุรินทร์', 'Surin', 'North-East', 'สำโรงทาบ', 'Samrong Thap');
INSERT INTO amphur VALUES ('หนองคาย', 'Nong Khai', 'North-East', 'ท่าบ่อ', 'Tha Bo');
INSERT INTO amphur VALUES ('หนองคาย', 'Nong Khai', 'North-East', 'เฝ้าไร่', 'Fao Rai');
INSERT INTO amphur VALUES ('หนองคาย', 'Nong Khai', 'North-East', 'โพธิ์ตาก', 'Pho Tak');
INSERT INTO amphur VALUES ('หนองคาย', 'Nong Khai', 'North-East', 'โพนพิสัย', 'Phon Phisai');
INSERT INTO amphur VALUES ('หนองคาย', 'Nong Khai', 'North-East', 'เมืองหนองคาย', 'Mueang Nong Khai');
INSERT INTO amphur VALUES ('หนองคาย', 'Nong Khai', 'North-East', 'รัตนวาปี', 'Rattanawapi');
INSERT INTO amphur VALUES ('หนองคาย', 'Nong Khai', 'North-East', 'ศรีเชียงใหม่', 'Si Chiang Mai');
INSERT INTO amphur VALUES ('หนองคาย', 'Nong Khai', 'North-East', 'สระใคร', 'Sakhrai');
INSERT INTO amphur VALUES ('หนองคาย', 'Nong Khai', 'North-East', 'สังคม', 'Sangkhom');
INSERT INTO amphur VALUES ('หนองบัวลำภู', 'Nong Bua Lamphu', 'North-East', 'นากลาง', 'Na Klang');
INSERT INTO amphur VALUES ('หนองบัวลำภู', 'Nong Bua Lamphu', 'North-East', 'นาวัง', 'Na Wang');
INSERT INTO amphur VALUES ('หนองบัวลำภู', 'Nong Bua Lamphu', 'North-East', 'โนนสัง', 'Non Sang');
INSERT INTO amphur VALUES ('หนองบัวลำภู', 'Nong Bua Lamphu', 'North-East', 'เมืองหนองบัวลำภู', 'Mueang Nongbua Lamphu');
INSERT INTO amphur VALUES ('หนองบัวลำภู', 'Nong Bua Lamphu', 'North-East', 'ศรีบุญเรือง', 'Si Bun Rueang');
INSERT INTO amphur VALUES ('หนองบัวลำภู', 'Nong Bua Lamphu', 'North-East', 'สุวรรณคูหา', 'Suwannakhuha');
INSERT INTO amphur VALUES ('อ่างทอง', 'Ang Thong', 'Centre', 'ไชโย', 'Chaiyo');
INSERT INTO amphur VALUES ('อ่างทอง', 'Ang Thong', 'Centre', 'ป่าโมก', 'Pa Mok');
INSERT INTO amphur VALUES ('อ่างทอง', 'Ang Thong', 'Centre', 'โพธิ์ทอง', 'Pho Thong');
INSERT INTO amphur VALUES ('อ่างทอง', 'Ang Thong', 'Centre', 'เมืองอ่างทอง', 'Mueang Ang Thong');
INSERT INTO amphur VALUES ('อ่างทอง', 'Ang Thong', 'Centre', 'วิเศษชัยชาญ', 'Wiset Chai Chan');
INSERT INTO amphur VALUES ('อ่างทอง', 'Ang Thong', 'Centre', 'สามโก้', 'Samko');
INSERT INTO amphur VALUES ('อ่างทอง', 'Ang Thong', 'Centre', 'แสวงหา', 'Sawaeng Ha');
INSERT INTO amphur VALUES ('อำนาจเจริญ', 'Amnat Charoen', 'North-East', 'ชานุมาน', 'Chanuman');
INSERT INTO amphur VALUES ('อำนาจเจริญ', 'Amnat Charoen', 'North-East', 'ปทุมราชวงศา', 'Pathum Ratchawongsa');
INSERT INTO amphur VALUES ('อำนาจเจริญ', 'Amnat Charoen', 'North-East', 'พนา', 'Phana');
INSERT INTO amphur VALUES ('อำนาจเจริญ', 'Amnat Charoen', 'North-East', 'เมืองอำนาจเจริญ', 'Mueang Amnat Charoen');
INSERT INTO amphur VALUES ('อำนาจเจริญ', 'Amnat Charoen', 'North-East', 'ลืออำนาจ', 'Lue Amnat');
INSERT INTO amphur VALUES ('อำนาจเจริญ', 'Amnat Charoen', 'North-East', 'เสนางคนิคม', 'Senangkhanikhom');
INSERT INTO amphur VALUES ('อำนาจเจริญ', 'Amnat Charoen', 'North-East', 'หัวตะพาน', 'Hua Taphan');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'กุดจับ', 'Kut Chap');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'กุมภวาปี', 'Kumphawapi');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'กู่แก้ว', 'Ku Kaeo');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'ไชยวาน', 'Chai Wan');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'ทุ่งฝน', 'Thung Fon');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'นายูง', 'Na Yung');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'น้ำโสม', 'Nam Som');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'โนนสะอาด', 'Non Sa-at');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'บ้านดุง', 'Ban Dung');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'บ้านผือ', 'Ban Phue');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'ประจักษ์ศิลปาคม', 'Prachaksinlapakhom');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'พิบูลย์รักษ์', 'Phibun Rak');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'เพ็ญ', 'Phen');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'เมืองอุดรธานี', 'Mueang Udon Thani');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'วังสามหมอ', 'Wang Sam Mo');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'ศรีธาตุ', 'Si That');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'สร้างคอม', 'Sang Khom');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'หนองวัวซอ', 'Nong Wua So');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'หนองแสง', 'Nong Saeng');
INSERT INTO amphur VALUES ('อุดรธานี', 'Udon Thani', 'North-East', 'หนองหาน', 'Nong Han');
INSERT INTO amphur VALUES ('อุตรดิตถ์', 'Uttaradit', 'North', 'ตรอน', 'Tron');
INSERT INTO amphur VALUES ('อุตรดิตถ์', 'Uttaradit', 'North', 'ทองแสนขัน', 'Thong Saen Khan');
INSERT INTO amphur VALUES ('อุตรดิตถ์', 'Uttaradit', 'North', 'ท่าปลา', 'Tha Pla');
INSERT INTO amphur VALUES ('อุตรดิตถ์', 'Uttaradit', 'North', 'น้ำปาด', 'Nam Pat');
INSERT INTO amphur VALUES ('อุตรดิตถ์', 'Uttaradit', 'North', 'บ้านโคก', 'Ban Khok');
INSERT INTO amphur VALUES ('อุตรดิตถ์', 'Uttaradit', 'North', 'พิชัย', 'Phichai');
INSERT INTO amphur VALUES ('อุตรดิตถ์', 'Uttaradit', 'North', 'ฟากท่า', 'Fak Tha');
INSERT INTO amphur VALUES ('อุตรดิตถ์', 'Uttaradit', 'North', 'เมืองอุตรดิตถ์', 'Mueang Uttaradit');
INSERT INTO amphur VALUES ('อุตรดิตถ์', 'Uttaradit', 'North', 'ลับแล', 'Laplae');
INSERT INTO amphur VALUES ('อุทัยธานี', 'Uthai Thani', 'Centre', 'ทัพทัน', 'Thap Than');
INSERT INTO amphur VALUES ('อุทัยธานี', 'Uthai Thani', 'Centre', 'บ้านไร่', 'Ban Rai');
INSERT INTO amphur VALUES ('อุทัยธานี', 'Uthai Thani', 'Centre', 'เมืองอุทัยธานี', 'Mueang Uthai Thani');
INSERT INTO amphur VALUES ('อุทัยธานี', 'Uthai Thani', 'Centre', 'ลานสัก', 'Lan Sak');
INSERT INTO amphur VALUES ('อุทัยธานี', 'Uthai Thani', 'Centre', 'สว่างอารมณ์', 'Sawang Arom');
INSERT INTO amphur VALUES ('อุทัยธานี', 'Uthai Thani', 'Centre', 'หนองขาหย่าง', 'Nong Khayang');
INSERT INTO amphur VALUES ('อุทัยธานี', 'Uthai Thani', 'Centre', 'หนองฉาง', 'Nong Chang');
INSERT INTO amphur VALUES ('อุทัยธานี', 'Uthai Thani', 'Centre', 'ห้วยคต', 'Huai Khot');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'กุดข้าวปุ้น', 'Kut Khaopun');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'เขมราฐ', 'Khemarat');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'เขื่องใน', 'Khueang Nai');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'โขงเจียม', 'Khong Chiam');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'ดอนมดแดง', 'Don Mot Daeng');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'เดชอุดม', 'Det Udom');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'ตระการพืชผล', 'Trakan Phuet Phon');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'ตาลสุม', 'Tan Sum');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'ทุ่งศรีอุดม', 'Thung Si Udom');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'นาจะหลวย', 'Na Chaluai');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'นาตาล', 'Na Tan');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'นาเยีย', 'Na Yia');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'น้ำขุ่น', 'Nam Khun');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'น้ำยืน', 'Nam Yuen');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'บุณฑริก', 'Buntharik');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'พิบูลมังสาหาร', 'Phibun Mangsahan');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'โพธิ์ไทร', 'Pho Sai');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'ม่วงสามสิบ', 'Muang Sam Sip');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'เมืองอุบลราชธานี', 'Mueang Ubon Ratchathani');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'วารินชำราบ', 'Warin Chamrap');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'ศรีเมืองใหม่', 'Si Mueang Mai');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'สว่างวีระวงศ์', 'Sawang Wirawong');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'สำโรง', 'Samrong');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'สิรินธร', 'Sirindhorn');
INSERT INTO amphur VALUES ('อุบลราชธานี', 'Ubon Ratchathani', 'North-East', 'เหล่าเสือโก้ก', 'Lao Suea Kok');

