drop table if exists starbucks;

CREATE TABLE starbucks (
    menu varchar(65),
    category varchar(5),
    calories real,
    fat_g real,
    carb_g real,
    fiber_g real,
    protein_g real,
    sodium real
);


INSERT INTO starbucks VALUES ('Cool Lime Starbucks Refreshers™ Beverage', 'drink', 45, 0, 11, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Ombré Pink Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Pink Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Strawberry Acai Starbucks Refreshers™ Beverage', 'drink', 80, 0, 18, 1, NULL, 10);
INSERT INTO starbucks VALUES ('Very Berry Hibiscus Starbucks Refreshers™ Beverage', 'drink', 60, 0, 14, 1, NULL, 10);
INSERT INTO starbucks VALUES ('Violet Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Evolution Fresh™ Cold-Pressed Apple Berry Juice', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Evolution Fresh™ Defense Up', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Evolution Fresh™ Organic Ginger Limeade', 'drink', 110, 0, 28, 0, NULL, 5);
INSERT INTO starbucks VALUES ('Iced Coffee', 'drink', 0, 0, 0, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Iced Coffee with Milk', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Iced Espresso Classics - Vanilla Latte', 'drink', 130, 2.5, 21, 0, NULL, 65);
INSERT INTO starbucks VALUES ('Iced Espresso Classics - Caffe Mocha', 'drink', 140, 2.5, 23, 0, NULL, 90);
INSERT INTO starbucks VALUES ('Iced Espresso Classics - Caramel Macchiato', 'drink', 130, 2.5, 21, 0, NULL, 65);
INSERT INTO starbucks VALUES ('Starbucks® Caramel Iced Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Iced Coffee + Milk', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Low Calorie Iced Coffee + Milk', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Vanilla Iced Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Shaken Sweet Tea', 'drink', 80, 0, 19, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Tazo® Bottled Berry Blossom White', 'drink', 60, 0, 15, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Tazo® Bottled Black Mango', 'drink', 150, 0, 38, 0, NULL, 15);
INSERT INTO starbucks VALUES ('Tazo® Bottled Black with Lemon', 'drink', 140, 0, 35, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Tazo® Bottled Brambleberry', 'drink', 140, 0, 35, 0, NULL, 15);
INSERT INTO starbucks VALUES ('Tazo® Bottled Giant Peach', 'drink', 150, 0, 37, 0, NULL, 15);
INSERT INTO starbucks VALUES ('Tazo® Bottled Iced Passion', 'drink', 70, 0, 17, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Tazo® Bottled Lemon Ginger', 'drink', 120, 0, 31, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Tazo® Bottled Organic Black Lemonade', 'drink', 140, 0, 35, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Tazo® Bottled Organic Iced Black Tea', 'drink', 60, 0, 15, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Tazo® Bottled Organic Iced Green Tea', 'drink', 120, 0, 31, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Tazo® Bottled Plum Pomegranate', 'drink', 140, 0, 35, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Tazo® Bottled Tazoberry', 'drink', 150, 0, 38, 0, NULL, 15);
INSERT INTO starbucks VALUES ('Tazo® Bottled White Cranberry', 'drink', 140, 0, 35, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Teavana® Shaken Iced Black Tea', 'drink', 30, 0, 8, 0, NULL, 5);
INSERT INTO starbucks VALUES ('Teavana® Shaken Iced Black Tea Lemonade', 'drink', 70, 0, 17, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Teavana® Shaken Iced Green Tea', 'drink', 30, 0, 8, 0, NULL, 5);
INSERT INTO starbucks VALUES ('Teavana® Shaken Iced Green Tea Lemonade', 'drink', 70, 0, 17, 0, NULL, 5);
INSERT INTO starbucks VALUES ('Teavana® Shaken Iced Passion Tango™ Tea', 'drink', 30, 0, 8, 0, NULL, 5);
INSERT INTO starbucks VALUES ('Teavana® Shaken Iced Passion Tango™ Tea Lemonade', 'drink', 90, 0, 24, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Teavana® Shaken Iced Peach Green Tea', 'drink', 60, 0, 15, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Iced Espresso Classics - Skinny Caramel Macchiato', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Iced Espresso Classics - Skinny Vanilla Latte', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Energy Coffee Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Energy Mexican Mocha', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Energy Mocha Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Energy Vanilla Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Energy White Chocolate Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Energy+Cinnamon Dolce Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Espresso Cubano', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Espresso Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Espresso Salted Caramel Cream', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Light Espresso Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® Protein Caramel', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Refreshers™ Raspberry Pomegranate', 'drink', 90, 0, 27, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Starbucks Refreshers™ Strawberry Lemonade', 'drink', 90, 0, 27, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Starbucks® Bottled Caramel Frappuccino® Coffee Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Bottled Coffee Frappuccino® Coffee Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Bottled Cold Brew Black, Unsweetened', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Bottled Cold Brew Cocoa and Honey with Cream', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Bottled Dulce de Leche Frappuccino® Coffee Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Bottled Mocha Frappuccino® Coffee Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Bottled Mocha Light Frappuccino® Coffee Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Bottled S''mores Frappuccino® Coffee Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Bottled Vanilla Frappuccino® Coffee Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Bottled Vanilla Light Frappuccino® Coffee Drink', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks® Doubleshot Protein Dark Chocolate', 'drink', 210, 2.5, 33, 2, NULL, 115);
INSERT INTO starbucks VALUES ('Starbucks® Doubleshot Protein Vanilla', 'drink', 200, 2.5, 34, 2, NULL, 120);
INSERT INTO starbucks VALUES ('Starbucks® Iced Coffee Caramel', 'drink', 60, 0, 13, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Starbucks® Iced Coffee Light Sweetened', 'drink', 50, 0, 11, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Starbucks® Iced Coffee Unsweetened', 'drink', 10, 0, 2, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Starbucks® Refreshers™ - Black Cherry Limeade with Coconut Water', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Teavana® Mango Black Tea', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Teavana® Passion Tango® Herbal Tea', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Teavana® Peach Green Tea', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('White Chocolate Mocha Bottled Frappuccino', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Blonde Roast', 'drink', 5, 0, 0, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Caffè Misto', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Clover® Brewed Coffee', 'drink', 10, 0, 0, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Coffee Traveler', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Decaf Pike Place® Roast', 'drink', 5, 0, 0, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Featured Dark Roast', 'drink', 5, 0, 0, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Iced Coffee', 'drink', 5, 0, 0, 0, NULL, 5);
INSERT INTO starbucks VALUES ('Nariño 70 Cold Brew', 'drink', 5, 0, 0, 0, NULL, 15);
INSERT INTO starbucks VALUES ('Nariño 70 Cold Brew with Milk', 'drink', 0, 0, 0, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Nitro Cold Brew', 'drink', 5, 0, 0, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Nitro Cold Brew with Sweet Cream', 'drink', 70, 5, 5, 0, NULL, 20);
INSERT INTO starbucks VALUES ('Pike Place® Roast', 'drink', 5, 0, 0, 0, NULL, 10);
INSERT INTO starbucks VALUES ('Toasted Coconut Cold Brew', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Vanilla Sweet Cream Cold Brew', 'drink', 110, 6, 14, 0, NULL, 25);
INSERT INTO starbucks VALUES ('Hot Chocolate', 'drink', 320, 9, 47, 4, NULL, 160);
INSERT INTO starbucks VALUES ('Starbucks® Signature Hot Chocolate', 'drink', 430, 26, 45, 5, NULL, 115);
INSERT INTO starbucks VALUES ('Caffè Americano', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Caffè Latte', 'drink', 190, 7, 19, 0, NULL, 170);
INSERT INTO starbucks VALUES ('Caffè Mocha', 'drink', 290, 8, 42, 4, NULL, 140);
INSERT INTO starbucks VALUES ('Cappuccino', 'drink', 120, 4, 12, 0, NULL, 100);
INSERT INTO starbucks VALUES ('Caramel Macchiato', 'drink', 250, 7, 35, 0, NULL, 150);
INSERT INTO starbucks VALUES ('Cascara Coconutmilk Latte', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Cinnamon Dolce Latte', 'drink', 260, 6, 40, 0, NULL, 150);
INSERT INTO starbucks VALUES ('Coconutmilk Mocha Macchiato', 'drink', 250, 9, 32, 0, NULL, 180);
INSERT INTO starbucks VALUES ('Espresso', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Espresso Con Panna', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Espresso Macchiato', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Flat White', 'drink', 180, 7, 18, 0, NULL, 160);
INSERT INTO starbucks VALUES ('Iced Caffè Americano', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Iced Caffè Latte', 'drink', 130, 4.5, 13, 0, NULL, 115);
INSERT INTO starbucks VALUES ('Iced Caffè Mocha', 'drink', 230, 6, 36, 4, NULL, 90);
INSERT INTO starbucks VALUES ('Iced Caramel Macchiato', 'drink', 250, 7, 37, 0, NULL, 150);
INSERT INTO starbucks VALUES ('Iced Cascara Coconutmilk Latte', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Iced Cinnamon Dolce Latte', 'drink', 200, 4, 34, 0, NULL, 95);
INSERT INTO starbucks VALUES ('Iced Coconutmilk Mocha Macchiato', 'drink', 260, 9, 34, 0, NULL, 180);
INSERT INTO starbucks VALUES ('Iced Skinny Cinnamon Dolce Latte', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Iced Skinny Mocha', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Iced Vanilla Latte', 'drink', 190, 4, 30, 0, NULL, 100);
INSERT INTO starbucks VALUES ('Iced White Chocolate Mocha', 'drink', 300, 8, 47, 0, NULL, 190);
INSERT INTO starbucks VALUES ('Latte Macchiato', 'drink', 190, 7, 19, 0, NULL, 160);
INSERT INTO starbucks VALUES ('Skinny Mocha', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Starbucks Doubleshot® on Ice Beverage', 'drink', 45, 1, 5, 0, NULL, 40);
INSERT INTO starbucks VALUES ('Vanilla Latte', 'drink', 250, 6, 37, 0, NULL, 150);
INSERT INTO starbucks VALUES ('White Chocolate Mocha', 'drink', 360, 11, 53, 0, NULL, 240);
INSERT INTO starbucks VALUES ('Caffè Vanilla Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Caffè Vanilla Light Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Caramel Cocoa Cluster Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Caramel Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Caramel Light Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Chai Crème Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Cinnamon Dolce Frappuccino® Blended Coffee', 'drink', 350, 4.5, 64, 0, NULL, 0);
INSERT INTO starbucks VALUES ('Cinnamon Dolce Light Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Cinnamon Roll Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Coffee Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Coffee Light Frappuccino® Blended Coffee', 'drink', 110, 0, 24, 0, NULL, 200);
INSERT INTO starbucks VALUES ('Cupcake Crème Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Green Tea Crème Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Java Chip Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Java Chip Light Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Lemon Bar Crème Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Midnight Mint Mocha Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Midnight Mint Mocha Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Mocha Frappuccino® Blended Coffee', 'drink', 280, 2.5, 60, 2, NULL, 220);
INSERT INTO starbucks VALUES ('Mocha Light Frappuccino® Blended Coffee', 'drink', 140, 0.5, 28, 1, NULL, 180);
INSERT INTO starbucks VALUES ('Oprah Cinnamon Chai Crème Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Red Velvet Cake Crème Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('S''mores Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('S''mores Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Strawberries & Crème Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('The Pokémon™ GO Frappuccino® Blended Beverage', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Vanilla Bean Crème Frappuccino® Blended Crème', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('White Chocolate Mocha Frappuccino® Blended Coffee', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Cinnamon Dolce Crème', 'drink', 200, 6, 28, 0, NULL, 135);
INSERT INTO starbucks VALUES ('Organic Chocolate Milk Box', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Steamed Apple Juice', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Vanilla Crème', 'drink', 200, 6, 28, 0, NULL, 135);
INSERT INTO starbucks VALUES ('Chocolate Smoothie', 'drink', 320, 5, 53, 8, NULL, 170);
INSERT INTO starbucks VALUES ('Strawberry Smoothie', 'drink', 300, 2, 60, 7, NULL, 130);
INSERT INTO starbucks VALUES ('Ginger Ale', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Lemon Ale', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Orange Cream Soda', 'drink', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO starbucks VALUES ('Chonga Bagel', 'food', 300, 5, 50, 3, 12, NULL);
INSERT INTO starbucks VALUES ('8-Grain Roll', 'food', 380, 6, 70, 7, 10, NULL);
INSERT INTO starbucks VALUES ('Almond Croissant', 'food', 410, 22, 45, 3, 10, NULL);
INSERT INTO starbucks VALUES ('Apple Fritter', 'food', 460, 23, 56, 2, 7, NULL);
INSERT INTO starbucks VALUES ('Banana Nut Bread', 'food', 420, 22, 52, 2, 6, NULL);
INSERT INTO starbucks VALUES ('Blueberry Muffin with Yogurt and Honey', 'food', 380, 16, 53, 1, 6, NULL);
INSERT INTO starbucks VALUES ('Blueberry Scone', 'food', 420, 17, 61, 2, 5, NULL);
INSERT INTO starbucks VALUES ('Butter Croissant', 'food', 240, 12, 28, 1, 5, NULL);
INSERT INTO starbucks VALUES ('Butterfly Cookie', 'food', 350, 22, 38, 0, 2, NULL);
INSERT INTO starbucks VALUES ('Cheese Danish', 'food', 320, 16, 36, 1, 8, NULL);
INSERT INTO starbucks VALUES ('Chewy Chocolate Cookie', 'food', 170, 5, 30, 2, 2, NULL);
INSERT INTO starbucks VALUES ('Chocolate Chip Cookie', 'food', 310, 15, 42, 2, 4, NULL);
INSERT INTO starbucks VALUES ('Chocolate Chunk Muffin', 'food', 440, 21, 60, 2, 7, NULL);
INSERT INTO starbucks VALUES ('Chocolate Croissant', 'food', 330, 18, 38, 1, 6, NULL);
INSERT INTO starbucks VALUES ('Chocolate Hazelnut Croissant', 'food', 390, 22, 43, 2, 7, NULL);
INSERT INTO starbucks VALUES ('Chocolate Marble Loaf Cake', 'food', 490, 24, 64, 2, 6, NULL);
INSERT INTO starbucks VALUES ('Cinnamon Morning Bun', 'food', 390, 15, 56, 2, 8, NULL);
INSERT INTO starbucks VALUES ('Cinnamon Raisin Bagel', 'food', 270, 1, 58, 3, 9, NULL);
INSERT INTO starbucks VALUES ('Classic Coffee Cake', 'food', 390, 16, 57, 1, 5, NULL);
INSERT INTO starbucks VALUES ('Cookie Butter Bar', 'food', 360, 23, 36, 0, 2, NULL);
INSERT INTO starbucks VALUES ('Cranberry Orange Scone', 'food', 420, 15, 64, 1, 6, NULL);
INSERT INTO starbucks VALUES ('Devil''s Food Doughnut', 'food', 430, 23, 53, 2, 5, NULL);
INSERT INTO starbucks VALUES ('Double Chocolate Brownie', 'food', 410, 24, 46, 3, 6, NULL);
INSERT INTO starbucks VALUES ('Double Chocolate Chunk Brownie', 'food', 490, 28, 55, 3, 7, NULL);
INSERT INTO starbucks VALUES ('Double Chocolate Loaf Cake', 'food', 440, 23, 54, 3, 5, NULL);
INSERT INTO starbucks VALUES ('Everybody''s Favorite - Bantam Bagel (2 Pack)', 'food', 100, 3.5, 14, 0, 3, NULL);
INSERT INTO starbucks VALUES ('Everything Bagel with Cheese', 'food', 290, 3.5, 53, 2, 11, NULL);
INSERT INTO starbucks VALUES ('Frappuccino® Cookie Straw', 'food', 90, 3, 14, 0, 1, NULL);
INSERT INTO starbucks VALUES ('French Toast - Bantam Bagels (2 Pack)', 'food', 200, 8, 30, 0, 6, NULL);
INSERT INTO starbucks VALUES ('Gluten-Free Marshmallow Dream Bar', 'food', 240, 5, 45, 0, 2, NULL);
INSERT INTO starbucks VALUES ('Ice Cream Cone Sugar Cookie', 'food', 250, 14, 29, 1, 3, NULL);
INSERT INTO starbucks VALUES ('Iced Lemon Pound Cake', 'food', 470, 20, 68, 1, 6, NULL);
INSERT INTO starbucks VALUES ('Michigan Cherry Oat Bar', 'food', 310, 10, 47, 2, 3, NULL);
INSERT INTO starbucks VALUES ('Multigrain Bagel', 'food', 350, 4, 64, 8, 17, NULL);
INSERT INTO starbucks VALUES ('Oatmeal Cookie', 'food', 290, 12, 40, 3, 5, NULL);
INSERT INTO starbucks VALUES ('Octopus Cookie', 'food', 330, 18, 39, 1, 3, NULL);
INSERT INTO starbucks VALUES ('Old-Fashioned Glazed Doughnut', 'food', 480, 27, 56, 1, 5, NULL);
INSERT INTO starbucks VALUES ('Peanut butter cup cookie', 'food', 360, 21, 36, 3, 8, NULL);
INSERT INTO starbucks VALUES ('Pecan Tart', 'food', 330, 18, 39, 1, 4, NULL);
INSERT INTO starbucks VALUES ('Petite Vanilla Bean Scone', 'food', 120, 4.5, 18, 0, 2, NULL);
INSERT INTO starbucks VALUES ('Plain Bagel', 'food', 280, 1.5, 56, 2, 9, NULL);
INSERT INTO starbucks VALUES ('Pumpkin Bread', 'food', 410, 15, 63, 2, 6, NULL);
INSERT INTO starbucks VALUES ('Raspberry Swirl Loaf Cake', 'food', 420, 17, 61, 1, 6, NULL);
INSERT INTO starbucks VALUES ('Raspberry Whoopie Pie', 'food', 360, 18, 45, 1, 3, NULL);
INSERT INTO starbucks VALUES ('Reduced-Fat Cinnamon Swirl Coffee Cake', 'food', 370, 9, 67, 2, 5, NULL);
INSERT INTO starbucks VALUES ('S''mores Bar', 'food', 330, 17, 44, 1, 2, NULL);
INSERT INTO starbucks VALUES ('S''mores Bar Multipack', 'food', 330, 17, 44, 1, 2, NULL);
INSERT INTO starbucks VALUES ('Sprouted Grain Vegan Bagel', 'food', 330, 6, 57, 7, 12, NULL);
INSERT INTO starbucks VALUES ('Strawberry Cake Pop', 'food', 180, 9, 23, 0, 2, NULL);
INSERT INTO starbucks VALUES ('The Classic - Bantam Bagels (2 Pack)', 'food', 200, 8, 28, 0, 6, NULL);
INSERT INTO starbucks VALUES ('Toffeedoodle', 'food', 300, 13, 44, 1, 3, NULL);
INSERT INTO starbucks VALUES ('Vanilla Bean Whoopie Pie', 'food', 360, 18, 45, 1, 3, NULL);
INSERT INTO starbucks VALUES ('Vermont Maple Walnut Muffin', 'food', 390, 21, 45, 2, 6, NULL);
INSERT INTO starbucks VALUES ('Volpi™ Pepperoni & Tomato Savory Foldover', 'food', 270, 14, 27, 2, 10, NULL);
INSERT INTO starbucks VALUES ('Strawberries & Jam Sandwich', 'food', 600, 25, 80, 10, 19, NULL);
INSERT INTO starbucks VALUES ('Burrata & Basil Pesto Small Sandwich', 'food', 300, 14, 34, 2, 11, NULL);
INSERT INTO starbucks VALUES ('Cage-Free Eggs & Seasoned Grains Side Salad', 'food', 360, 18, 33, 3, 17, NULL);
INSERT INTO starbucks VALUES ('Cauliflower Tabbouleh Side Salad', 'food', 130, 12, 7, 3, 2, NULL);
INSERT INTO starbucks VALUES ('Cubano Sandwich', 'food', 430, 23, 34, 3, 21, NULL);
INSERT INTO starbucks VALUES ('Farmers'' Market Protein Box', 'food', 470, 29, 29, 4, 21, NULL);
INSERT INTO starbucks VALUES ('Garden Greens & Shaved Parmesan Side Salad', 'food', 170, 13, 9, 2, 7, NULL);
INSERT INTO starbucks VALUES ('Green Goddess Avocado Salad', 'food', 620, 37, 62, 10, 13, NULL);
INSERT INTO starbucks VALUES ('Herbed Chicken & Fig Spread Small Sandwich', 'food', 300, 8, 43, 2, 19, NULL);
INSERT INTO starbucks VALUES ('Honey BBQ Sriracha Chicken Sandwich', 'food', 360, 7, 52, 3, 22, NULL);
INSERT INTO starbucks VALUES ('Roasted Carrot & Kale Side Salad', 'food', 440, 26, 44, 7, 10, NULL);
INSERT INTO starbucks VALUES ('Roasted Turkey & Dill Havarti Sandwich', 'food', 600, 32, 47, 6, 32, NULL);
INSERT INTO starbucks VALUES ('Seared Steak & Cheddar Sandwich', 'food', 530, 29, 44, 2, 23, NULL);
INSERT INTO starbucks VALUES ('Slow-Roasted Ham & Beecher''s Flagship Cheese Small Sandwich', 'food', 350, 18, 31, 1, 16, NULL);
INSERT INTO starbucks VALUES ('Smoked Mozzarella & Roasted Pepper Sandwich', 'food', 500, 28, 46, 4, 18, NULL);
INSERT INTO starbucks VALUES ('Turkey & Fire-Roasted Corn Salad', 'food', 560, 29, 53, 7, 24, NULL);
INSERT INTO starbucks VALUES ('Za''atar Chicken & Lemon Tahini Salad', 'food', 570, 23, 67, 11, 27, NULL);
INSERT INTO starbucks VALUES ('BBQ Chicken Protein Box', 'food', 420, 16, 49, 5, 22, NULL);
INSERT INTO starbucks VALUES ('Cheese & Fruit Protein Box', 'food', 450, 27, 34, 4, 20, NULL);
INSERT INTO starbucks VALUES ('Chicken Wrap Protein Box', 'food', 460, 22, 45, 4, 20, NULL);
INSERT INTO starbucks VALUES ('Eggs & Cheese Protein Box', 'food', 460, 24, 40, 5, 23, NULL);
INSERT INTO starbucks VALUES ('PB&J Protein Box', 'food', 520, 26, 53, 5, 20, NULL);
INSERT INTO starbucks VALUES ('Smoked Turkey Protein Box', 'food', 360, 12, 42, 5, 24, NULL);
INSERT INTO starbucks VALUES ('Birthday Cake Pop', 'food', 170, 9, 23, 0, 1, NULL);
INSERT INTO starbucks VALUES ('Chocolate Cake Pop', 'food', 160, 8, 23, 1, 2, NULL);
INSERT INTO starbucks VALUES ('Chocolate Chip Cookie Dough Cake Pop', 'food', 180, 9, 23, 0, 2, NULL);
INSERT INTO starbucks VALUES ('Pirate Cake Pop', 'food', 180, 9, 24, 0, 1, NULL);
INSERT INTO starbucks VALUES ('Bacon Gouda & Egg Breakfast Sandwich', 'food', 370, 19, 32, 1, 18, NULL);
INSERT INTO starbucks VALUES ('Certified Gluten-Free Breakfast Sandwich', 'food', 280, 13, 18, 6, 18, NULL);
INSERT INTO starbucks VALUES ('Classic Whole-Grain Oatmeal', 'food', 160, 2.5, 28, 4, 5, NULL);
INSERT INTO starbucks VALUES ('Double-Smoked Bacon Cheddar & Egg Sandwich', 'food', 490, 27, 40, 1, 21, NULL);
INSERT INTO starbucks VALUES ('Ham & Cheese Croissant', 'food', 320, 17, 28, 1, 14, NULL);
INSERT INTO starbucks VALUES ('Hearty Blueberry Oatmeal', 'food', 220, 2.5, 43, 5, 5, NULL);
INSERT INTO starbucks VALUES ('Reduced-Fat Turkey Bacon & Cage Free Egg White Breakfast Sandwich', 'food', 230, 6, 28, 2, 16, NULL);
INSERT INTO starbucks VALUES ('Sausage Cheddar & Egg Breakfast Sandwich', 'food', 500, 28, 41, 1, 15, NULL);
INSERT INTO starbucks VALUES ('Seared Steak Egg & Tomatillo Wrap', 'food', 410, 18, 43, 2, 21, NULL);
INSERT INTO starbucks VALUES ('Slow-Roasted Ham Swiss & Egg Breakfast Sandwich', 'food', 450, 23, 42, 1, 24, NULL);
INSERT INTO starbucks VALUES ('Sous Vide Egg Bites: Bacon & Gruyere', 'food', 310, 22, 9, 0, 19, NULL);
INSERT INTO starbucks VALUES ('Sous Vide Egg Bites: Egg White & Red Pepper', 'food', 170, 7, 13, 1, 13, NULL);
INSERT INTO starbucks VALUES ('Spicy Chorizo  Monterey Jack & Egg Breakfast Sandwich', 'food', 500, 30, 35, 3, 26, NULL);
INSERT INTO starbucks VALUES ('Spinach Feta & Cage Free Egg White Breakfast Wrap', 'food', 290, 10, 33, 6, 19, NULL);
INSERT INTO starbucks VALUES ('Ancho Chipotle Chicken Panini', 'food', 500, 19, 57, 4, 26, NULL);
INSERT INTO starbucks VALUES ('Chicken & Quinoa Protein Bowl with Black Beans and Greens', 'food', 420, 17, 42, 9, 27, NULL);
INSERT INTO starbucks VALUES ('Chicken Artichoke on Ancient Grain Flatbread', 'food', 510, 27, 37, 5, 24, NULL);
INSERT INTO starbucks VALUES ('Chicken BLT Salad Sandwich', 'food', 470, 25, 35, 3, 21, NULL);
INSERT INTO starbucks VALUES ('Egg Salad Sandwich', 'food', 480, 27, 42, 7, 16, NULL);
INSERT INTO starbucks VALUES ('Homestyle Chicken & Double-Smoked Bacon', 'food', 480, 17, 57, 3, 23, NULL);
INSERT INTO starbucks VALUES ('Italian-Style Ham & Spicy Salami', 'food', 480, 20, 49, 3, 22, NULL);
INSERT INTO starbucks VALUES ('Lentils & Vegetable Protein Bowl with Brown Rice', 'food', 650, 29, 80, 21, 23, NULL);
INSERT INTO starbucks VALUES ('Roasted Tomato & Mozzarella Panini', 'food', 420, 18, 47, 3, 11, NULL);
INSERT INTO starbucks VALUES ('Turkey & Havarti Sandwich', 'food', 460, 21, 31, 2, 29, NULL);
INSERT INTO starbucks VALUES ('Turkey Pesto Panini', 'food', 560, 23, 55, 3, 34, NULL);
INSERT INTO starbucks VALUES ('Berry Trio Yogurt', 'food', 240, 2.5, 39, 3, 14, NULL);
INSERT INTO starbucks VALUES ('Fresh Blueberries and Honey Greek Yogurt Parfait', 'food', 240, 2.5, 42, 2, 14, NULL);
INSERT INTO starbucks VALUES ('Justin''s Chocolate Hazelnut Butter', 'food', 180, 14, 12, 3, 4, NULL);
INSERT INTO starbucks VALUES ('Justin''s Classic Almond Butter', 'food', 190, 18, 6, 3, 7, NULL);
INSERT INTO starbucks VALUES ('Lemon Chiffon Yogurt', 'food', 340, 13, 38, 0, 18, NULL);
INSERT INTO starbucks VALUES ('Organic Avocado (Spread)', 'food', 90, 8, 5, 4, 1, NULL);
INSERT INTO starbucks VALUES ('Seasonal Fruit Blend', 'food', 90, 0, 24, 4, 1, NULL);
